### ISSUE TITLE
Interesting talk from @slurdge  at Pass-The-Salt '19

### ISSUE THREAD

**Issue by iceman1001** [iceman1001/ChameleonMini-rebooted#102]
Interesting talk from @slurdge  at Pass-The-Salt '19 about this repo!

Worth watching!
https://passthesalt.ubicast.tv/videos/reversing-a-firmware-uploader-others-nfc-stories/

**Comment by iceman1001** [comment]
I spoke with him at @PTS and he said he will make a writeup,   preferably on the wiki.
So all these confusing issues with scattered information is becomes a clear story

**Comment by securechicken** [comment]
@slurdge really interesting indeed. This puts a lot together if you want to understand the firmware flashing principle.

**Comment by iceman1001** [comment]
@slurdge   Did you make a writeup?

**Comment by slurdge** [comment]
Alas, not yet. Pretty busy with a new consulting. I hope around next week (I hope).

**Comment by iceman1001** [comment]
NP
