### ISSUE TITLE
Chameleon mini Rev G MF DETECTION

### ISSUE THREAD

**Issue by nico0481** [iceman1001/ChameleonMini-rebooted#113]
Hello,

Is the Chameleon mini **Rev G** able to do reader attack (MF Detection).
With which firmware?
I can't find a way to do this.

Thank you

Best regards

Nico

**Comment by iceman1001** [comment]
Technically yes,  implemented no.

**Comment by securechicken** [comment]
Dear @nico0481 , this repo is RevE rebooted. You might wanna try [https://github.com/emsec/ChameleonMini](https://github.com/emsec/ChameleonMini). Hope you will find your answers there.

@iceman1001 shall we close?

**Comment by nico0481** [comment]
Thanks guys!
