### ISSUE TITLE
[Question] "Reader Attack" Timing

### ISSUE THREAD

**Issue by czaur** [iceman1001/ChameleonMini-rebooted#118]
Hi.

Do you guys know if Chameleon when used in mode **MF_DETECTION** when approached near to the target reader, the red led blinks... what actually it's doing behind the scenes?
I mean, I'm doing some tests with Chameleon and reader attack with different NFC readers spread in the city. Till now I didn't manage to recover any key.

I didn't find the amount time holding Chameleon near to the reader. It makes any difference holding it for 10 seconds or 10 minutes?
My final question is: it makes any difference let Chameleon near to the target reader more and more minutes? It will make any difference when using **mfkey32** or **fast/exact recon**?

Thanks in advance.

**Comment by maxieds** [comment]
Have you tried reading the firmware source in C? It's available if you ever
have questions or need customizations.

**Comment by iceman1001** [comment]
if you read some of the older Mifare Classic attack papers,  you will find reference to a 32bits recovery and 64bits recover attack.

**Comment by czaur** [comment]
Since I recently acquire one, the purpose of my questions is helping Chameleon project documenting functionalities and discrepancies using the hardware in different scenarios.

**Comment by iceman1001** [comment]
Good initiative
