### ISSUE TITLE
Maybe a way How to flash a new firmware on the Chameleon on a linux-based OS?

### ISSUE THREAD

**Issue by ghost** [iceman1001/ChameleonMini-rebooted#12]
Hi

Maybe this is the way to flash on a linux based system:

1. Install DFU-Programmer (or be sure that the DFU-Programmer installation was successfull)

2. Activate Bootloader-mode on the ChameloenMini by holding down the button while powering on.
    (Black button)

3. Check/Confirm that the device is available 
    `lsusb`

4. Run the Firmware update / Program the device with dfu-programmer (maybe as root)
    `dfu-programmer atxmega32a4u erase`
    `dfu-programmer atxmega32a4u flash-eeprom Chameleon-Mini.eep`
    `dfu-programmer atxmega32a4u flash Chameleon-Mini.hex`
    `dfu-programmer atxmega32a4u reset`

I can’t test it because I don’t own a Rev. E Rebooted
If someone like to test / double check it won’t be great.

Maybe another way is available with avrdude but I actual have not enough time between Xmas.
Cheers

**Comment by bogiton** [comment]
Nah, this doesn't work for the rebooted device.
In fact, these are the same commands that the windows batch script uses for flashing the original Chameleon-Mini. Which -again- don't work for the rebooted device.
Not even the suggested way of flashing under Linux (using avrdude) works for the rebooted Chameleon.

**Comment by ghost** [comment]
@bogiton ok. What’s the difference between both devices that it wouldn’t work?

**Comment by bogiton** [comment]
Wish I knew. Well, apart from the fact that they are using a bit different MCU (atxmega32a4u instead of atxmega128a4u), as you may have noticed. Check issue #11, it is very relevant.

**Comment by iceman1001** [comment]
Those commands should work,  since we use un-altered hex/eep when compiling in Atmel Studio 7...

**Comment by securechicken** [comment]
@gtpy please read Wiki pages on flashing. This should be OK now.
@iceman1001 yet another close request.
