### ISSUE TITLE
converting commands

### ISSUE THREAD

**Issue by iceman1001** [iceman1001/ChameleonMini-rebooted#14]
The current CMDMY convention feels out of date and a hinder somewhat with having a unified way for tools that work with Chameleon Mini RevG,  or this rebooted version. 
There are not **real** cause for this change of commands more than locking in the rebooted firmware from the offical one.   With putting the rebooted software open-software again, the reason falls away.

However, I do feel we should keep all the extras which makes the rebooted so special,  like the mfkeys implementation.   I can also see we incoorporate the hardnested attack also into the client in the long run. 

What you think?

**Comment by bogiton** [comment]
I agree that the "MY" extension is unnecessary as well as kinda annoying. We should remove it.
I also agree that we should keep the rebooted extras, like the mfkey implementation, which by the way can be enabled by setting the "CONFIG_MF_DETECTION_SUPPORT" flag in the Makefile. Not sure if and how that works though.

**Comment by iceman1001** [comment]
Well,  we can always add our own commands in order to have the extras.   As long as we follow the official revG commands behavior in order to keep inter-operability.

**Comment by bogiton** [comment]
Indeed. Let's see if more people agree on that.

**Comment by iceman1001** [comment]
I suppose with so few ppl active, this is kind of an easy decision ;)

**Comment by ceres-c** [comment]
Agreed on both your proposals @iceman1001 
Sorry for my absence but I am really busy with exams in this period. Also, I highly doubt my skills are sufficient for giving proper input to this project. I'll still try to keep up with your updates and intervene when and if possible

**Comment by dunderhay** [comment]
+1 for same command set

**Comment by iceman1001** [comment]
@bogiton   what do you say?  time to drop the **MY** stuff?  you up for it?

**Comment by bogiton** [comment]
Ooh, yeah! Gladly! :)

**Comment by iceman1001** [comment]
@bogiton   great!  don't forget to update the GUI to work with this version aswell
