### ISSUE TITLE
[FORUM] Cannot set a 7-byte UID for MFC1k

### ISSUE THREAD

**Issue by wrenchii** [iceman1001/ChameleonMini-rebooted#144]
Hello! Just got to run my new chameleon mini rebooted. All is fairly straight forward, but while the description says it can emulate 7-byte UID Mifare Classic 1k cards, it refuses to accept anything other than 4-byte UIDs. Was I mislead into thinking it takes 7-byte UIDs? The LAB401 page says it does, but the GUI is not allowing me to (I tried both the iceman and the LAB401 GUIs with similar results).

**Comment by securechicken** [comment]
Dear @wrenchii ,

Please use correct issues buttons when they exist for your scenario, to help community better understand your concern.

A quick search on this repository, that I encourage you to systematically do before opening any new issue, raised this existing one where you will find some answers: #48 .

Please also note that this repository open source code, and generated "firmware", are not affiliated with any ChameleonMini seller, and are not distributing the official built-in firmware of the product you bought (i.e. we are not the LAB401 support, nor ChameleonMini original hardware or software). Do not hesitate to get in touch with seller's support to ask questions on the functionalities and capabilities for the product you bought, and how are the advertised functionalities supposed to work.
Best regards.

**Comment by wrenchii** [comment]
My sincere apologies. I understand that you are not representing support
for the vendors, I purely mentioned them for technical reference. Will
review what you had sent. Cheers and thanks for the support.

Sam

**Comment by securechicken** [comment]
No problem. Please close this issue if you found useful infos on 7b UID in referenced issue, and do not hesitate to open other ones to contribute fixing bugs or ask questions to the community on this repo's firmware.

**Comment by iceman1001** [comment]
Since you added default support for 7B in the firmware,  we can close this one.
