### ISSUE TITLE
draft of V1.4

### ISSUE THREAD

**Issue by iceman1001** [iceman1001/ChameleonMini-rebooted#158]
A draft for v1.4 release, codename MightGray of this firmware has been made.
@shinhub @bogiton @slurdge 
Feel free to update the text to cover all changes.

**Comment by iceman1001** [comment]
Those who are collaborators find it under code/releases  -- edit

**Comment by securechicken** [comment]
Done. Think I covered most of it (by going through closed PRs list...). Did not mention anything about boot loader, because it is not directly related to firmware, but a lot have been done there as well (we have a working source code for ChameleonMini RevE Rebooted, provided you can flash with AVRISPmkII).

**Comment by slurdge** [comment]
I must be blind, can't find where I should edit ❔

**Comment by iceman1001** [comment]
you weren't a collaborator.  You got invite.

**Comment by slurdge** [comment]
Nice 😄 
BTW super impressive work @shinhub ! I have to flash again my Mini

**Comment by securechicken** [comment]
Yeah I messed a lot with this firmware for a start,... I hope someone else than 1 or 2 recent issues openers and me will test that all before it is released in the wild :p

I would have expected the release to be nicknamed "Jean-Michel" though 😬

**Comment by iceman1001** [comment]
Jean-Michel the grey.   :)  And its still a draft who knows what happens

**Comment by bogiton** [comment]
Good job @shinhub! I believe you are the only one who can validate the changelog of this release. You did almost everything by yourself.

**Comment by securechicken** [comment]
Thanks! Well that's OK to me, but I think all of Mifare Ultralight work is from @McEloff, so... let him check as well. As for validating release, I would say let it be a few more days for users to identify bugs, and let release somewhere early October if everything fine till then.

**Comment by iceman1001** [comment]
We have no stress to make this release.  Let it sip in for a month.

**Comment by iceman1001** [comment]
No stress and over a year later,   with other issues instead.  
Somehow I get the feeling we ain't going to do a new release
