### ISSUE TITLE
[REQ] Mifare Classic S0/B0 should be readable without any authentication

### ISSUE THREAD

**Issue by securechicken** [iceman1001/ChameleonMini-rebooted#161]
### Description
The Block 0 in Sector 0 of any Mifare Classic emulated memory should be readable without any authentication, as expected by some readers, and implied by specs.

### Interest
This may fix some inconsistency with some readers, like MCT notably, and may be expected by some readers anyway.

### Possible implementation
Not sure if necessary to and how to "skip" the authenticating phase, as not sure how the readers would try to read S0/B0 without any auth. I see two possible behaviours: expecting any auth attempt to success if access to S0/B0 is requested, or not trying to auth at all and issuing a READ operation directly:
- S0/B0 access is requested by an AUTH operation in "ACTIVE" state: the application should directly jump to "AUTHED_IDLE" and set a bool to register the direct jump, to then only allow READ operation on S0/B0 in "AUTHED_IDLE";
- a "READ" command on S0/B0 is issued directly before any authentication attempt, and patched in "ACTIVE" state. The application should run the READ logic on S0/B0.

**Comment by iceman1001** [comment]
S0/B0  accessrights should follow what the ST is set for S0.  If  ACR is set non read,  than block0 shouldn't be read.

UID / SAQ /ATAQ is used in anticollision phase,  but that doesn't implose that S0/B0 should always be readable what called with a read command.

**Comment by securechicken** [comment]
OK, that was not so clear to me as MCT apparently tries to read it and fails to detect a valid tag if it can't.
I was mislead by this [slideshow](https://www.slideshare.net/GlenCifuentesToro/mifare-cards) from Gemalto (page 13), which says "_can be read without authenticating with sector 0_", but a remark (page 17) of [MF1S50YYX_V1](https://www.nxp.com/docs/en/data-sheet/MF1S50YYX_V1.pdf) says "_The Read from Block 0 in Sequence 2 does not require a prior authentication to Sector 0 and is transmitted in plain data. For all other sequences, the readout from Block 0 in Sector 0 is encrypted and requires an authentication to that sector_".

**Comment by iceman1001** [comment]
Let's see,  this issue wasn't the same as sak/atqa.  
That note is interesting,  1) its from Ev1 datasheet,  2) sequence 2 reference. 
What does older models datasheet say?
and which is sequence 1/2 ?

**Comment by securechicken** [comment]
- Sequence 1: ISO/IEC 14443-3 compliant anti-collision and selection using the cascade level 1 followed by the cascade level 2 SEL command
- Sequence 2: using cascade level 1 anti-collision and selection procedure followed by a Read command from block 0
- Sequence 3: ISO/IEC 14443-3 compliant anti-collision and selection using the cascade level 1 SEL command

From same page, cannot find any other reference. This for instance cannot be read in MF1S503x.
