### ISSUE TITLE
user manual found

### ISSUE THREAD

**Issue by iceman1001** [iceman1001/ChameleonMini-rebooted#17]
In the files people sent me, I found a user manual.  
[user manual](http://www.icedev.se/chameleon_mini_revE/chameleon_mini_rdv20.pdf)

**Comment by bogiton** [comment]
Wish I had that when I first got my Chameleon... Nice addition!

**Comment by iceman1001** [comment]
Me too

**Comment by iceman1001** [comment]
This user seem to have made a great usermanual.  We should be able to make a nice wiki from this!

[https://github.com/AndreasBujok/ChameleonMini](https://github.com/AndreasBujok/ChameleonMini)

**Comment by bogiton** [comment]
Indeed, looks a lot better now :)

**Comment by iceman1001** [comment]
Great!

**Comment by kevin2008-01** [comment]
Rhooooo ! thanks.
