### ISSUE TITLE
[BUG] Configuring dfu-programmar

### ISSUE THREAD

**Issue by CheckMatte2** [iceman1001/ChameleonMini-rebooted#172]
When i try to configure the dfu-programmar with ./bootstrap.sh as the instructions said i get this error ./bootstrap.sh: 2: aclocal: not found
./bootstrap.sh: 3: autoheader: not found
./bootstrap.sh: 4: automake: not found
./bootstrap.sh: 5: autoconf: not found
To install tab completion run
$ sudo mv dfu_programmer /etc/bash_completion.d/
To use tab completion in this terminal run
$ source dfu_programmer

if anyone knows the issue and is able to help that would be much apprecitated!

**Comment by CheckMatte2** [comment]
okay sorry im new to this site and i messed up and so here is my issue below

When i try to configure the dfu-programmar with ./bootstrap.sh as the instructions said i get this error ./bootstrap.sh: 2: aclocal: not found
./bootstrap.sh: 3: autoheader: not found
./bootstrap.sh: 4: automake: not found
./bootstrap.sh: 5: autoconf: not found
To install tab completion run
 $ sudo mv dfu_programmer /etc/bash_completion.d/
To use tab completion in this terminal run
 $ source dfu_programmer


 if anyone knows the issue and is able to help that would be much apprecitated!

**Comment by leegarrett** [comment]
Re-read the instructions, you forgot to install several packages that contain these programs.

**Comment by securechicken** [comment]
And this is not the correct place to troubleshot dfu-programmer related issues.
