### ISSUE TITLE
Reader attack mifare ultralight C

### ISSUE THREAD

**Issue by iNeedHelpX** [iceman1001/ChameleonMini-rebooted#177]
Hey wondering how this works? Do I need to dump the card first? Or do I just put in my cards uid? I need to get the keys from the reader. Problem is my card only shows 6/40 sectors. The rest need keys

**Comment by iceman1001** [comment]
reader attack Mifare UL?  Can you explain what you mean more precisly?

**Comment by iNeedHelpX** [comment]
I have a mifare ultralight C card. I need the keys

**Comment by iceman1001** [comment]
Thats gonna be hard.  No current solution to get UL-C keys exists.
You can sniff all the trafic and use it.

**Comment by iNeedHelpX** [comment]
![Screenshot_20191225-011312](https://user-images.githubusercontent.com/41366455/71450358-7b5ea300-272e-11ea-975c-307d2ceadee0.jpg)

**Comment by iNeedHelpX** [comment]
Hey here is a few screen caps from taginfo app. Im sorta new so im not sure what to make of this

![Screenshot_20191225-011320](https://user-images.githubusercontent.com/41366455/71450364-8d404600-272e-11ea-86c8-b02714478e03.jpg)
![Screenshot_20191225-011312](https://user-images.githubusercontent.com/41366455/71450365-93362700-272e-11ea-9470-996d45bbf392.jpg)

**Comment by iceman1001** [comment]
As mentioned the chameleon mini can't solve your problem. 

Closning this one.
