### ISSUE TITLE
[FORUM] Chameleon freezing with solid light

### ISSUE THREAD

**Issue by dealaddict** [iceman1001/ChameleonMini-rebooted#178]
Detects in Gui but freezes with only 6 slots showing and keeps processing

Only 1 slot light is on. Can't change slot.

Won't go into dfu bootloader tried the black button trick 

Rebooted Gui also can't fully load it to force it into bootloader

I tried rescuing it with Avrisp adapter by erasing and reloading both eep and hex files. Still same issue after next reconnection. 

Any suggestions?

![20191227_101338](https://user-images.githubusercontent.com/46821957/71527784-b200fe80-2891-11ea-9701-1dfa3872b369.jpg)

**Comment by iceman1001** [comment]
Seems like last release of the firmware made the chameleon unstable.
I have removed that offending release,  but nevertheless this indicates that the currect source code isn't stable either. @grspy

**Comment by securechicken** [comment]
You may have bricked it. Please try [this wiki page](https://github.com/iceman1001/ChameleonMini-rebooted/wiki/Getting-started#no-more-light-go-back-to-stock).
If that does not work, you will want to follow the AVRISP reset [described here](https://github.com/iceman1001/ChameleonMini-rebooted/wiki/How-to-program-with-AVRISP-mkII), using repo provided `ChameleonMiniRDV2.0_ATxmega32A4U.hex` as Flash image in programmer, and then fully running [this wiki page](https://github.com/iceman1001/ChameleonMini-rebooted/wiki/Getting-started#no-more-light-go-back-to-stock) again.

**Comment by iceman1001** [comment]
Imagine that...  someone changed their account...

**Comment by securechicken** [comment]
@iceman1001 just the name, to match with other accounts on the Internet!

**Comment by iceman1001** [comment]
if it wasn't for your avatar, I would have had a harder time recognize you ;)
