### ISSUE TITLE
Unable to set ATQA value

### ISSUE THREAD

**Issue by Asledin** [iceman1001/ChameleonMini-rebooted#182]
My test conditions
**OS**
Windows 10x64 version 1803 Build 17134.1365
**GUI**
Chameleon Mini Rebooted GUI - v 1.3.0.2 Iceman Edition 
**Device**
Chameleon Mini rebooted v 1.3 (Iceman: 7420671)

In "Serial" tab I enter the command `ATQA?` in the console
I get information

--> ATQA?
101:OK WITH TEXT
0044

Then
--> ATQA=0004
100:OK

Value changes only for the current active cell
Okay/ 

After that, if I disconnect the USB cable from ChameleonMini The value ATQA immediately returns to the original value. (0044)
This is an error, the ATQA parameter that I enter (0004) should be remembered after disconnecting USB cable from the computer

How to make sure that the entered ATQA value is saved even after disconnecting the device from the computer?

And I have a question
Which command can change the ATQA value for all cells at once.

**Comment by ca1e** [comment]
Hi,from the source I found the reason:the fw doesnt store the atqa value nor sak value , it just in the ram.so when you disconnect the USB(system power off),the value you set for atqa or sak is immediately missing.
and there doesnt have any  command can change value for all slots for now(the src doesnt implement it yet)
