### ISSUE TITLE
Incorrect list of supported cards

### ISSUE THREAD

**Issue by NeuerUser** [iceman1001/ChameleonMini-rebooted#184]
On the main README there is a section "Supported Cards and Codecs". That, however, links to a wiki entry from a different github repo (emsec). As far as I understand not all cards listed there are supported by the Rev E rebooted, e.g. the 15693 types.

It would be good to have a correct overview what is possible to do with the Rev E.

(And thanks for all your great work!)

**Comment by iceman1001** [comment]
Yes, that could become better.  Feel free to make a wiki entry for all current supported cards. 

Since its not an issue of the repo,  I will close this one.
