### ISSUE TITLE
Ultralight missing from latest releases

### ISSUE THREAD

**Issue by dealaddict** [iceman1001/ChameleonMini-rebooted#186]
Hi. Ultralight option seems to be missing from latest Firmware releases up until of November last year. I want to flash the latest firmware as apparently it fixed the switch button freezing issue but new releases dont have Ultralight option or I cant seem to find it in drop down menu.

any solution would be appreciated

**Comment by ca1e** [comment]
seems it disabled by default.
https://github.com/iceman1001/ChameleonMini-rebooted/blob/9f958e97704c33933b911fa0720614ecfb596e7a/Firmware/ChameleonMini/Makefile#L22
and for some reason,
https://github.com/iceman1001/ChameleonMini-rebooted/blob/9f958e97704c33933b911fa0720614ecfb596e7a/Firmware/ChameleonMini/Makefile#L20
so you can build your own fw to enable it,or may be release separately in the future.
