### ISSUE TITLE
Communication between Chameleon and for example Arduino?!

### ISSUE THREAD

**Issue by TipsTricksMore** [iceman1001/ChameleonMini-rebooted#187]
Hi there,
First of all thank you for the great work you did on the software and hardware side of chameleon! It’s just great to play around with it.

I took the project to expand my knowledge of pcb design and designed the pcb from ground up for my self. Just to learn more about pcb designing.
Everything works as expected! 

Now I developed the idea of adding a physical small display to the interface. 
Due to the lack of free pins on the ATxmega32U4 I definitely have to add another IC though.
First thought: Just a simple Atmega328. It makes it easy to play around with the Arduino IDE and offers some great librarys.

Now my question is if there’s any way to realise a communication between the “Arduino” and Chameleon. That would be great because someone could just set new UIDs, change slots etc. through simple send requests...

If not is there another IC sized method whether than using a pc and terminal you could think of?

Thanks a lot for your help!
Best,
Leo

**Comment by grspy** [comment]
You can operate Chameleon using terminal commands through the USB port. So, the communication between an Arduino and the Chameleon is definitely feasible as long as you are sending Serial commands. You can check the available commands here: https://github.com/iceman1001/ChameleonMini-rebooted/wiki/Terminal-Commands
