### ISSUE TITLE
The bootloader

### ISSUE THREAD

**Issue by BH2VSQ** [iceman1001/ChameleonMini-rebooted#188]
I'd like to make a ChameleonMini-rebooted by myself . If I need to program the bootloader by myself ?

**Comment by iceman1001** [comment]
I am not sure I understand your question.  
but if you making your own device,  you will also need to put software/firmware on it.

**Comment by 1248680677** [comment]
> I am not sure I understand your question.
> but if you making your own device, you will also need to put software/firmware on it.

But I have no idea how to put software/firmware on it .

**Comment by BH2VSQ** [comment]
> I am not sure I understand your question.
> but if you making your own device, you will also need to put software/firmware on it.

I have found this article "https://github.com/iceman1001/ChameleonMini-rebooted/wiki/How-to-program-with-AVRISP-mkII" , but I don't want to buy an AVRISP mkII to put software/firmware on it . Is there any other way to put software/firmware on it ？

**Comment by iceman1001** [comment]
not if you are building your own.
