### ISSUE TITLE
draft for release v1.0

### ISSUE THREAD

**Issue by iceman1001** [iceman1001/ChameleonMini-rebooted#19]
I guess current status should be a release,  it compiles and works with old GUI.

https://github.com/iceman1001/ChameleonMini-rebooted/releases/tag/untagged-09ff734155892b121c57

Tell me if its ok or not,  and what should change if not.

**Comment by kevin2008-01** [comment]
Hi, 404 error

**Comment by iceman1001** [comment]
hm,  can you see the draft on  /code/releases  ??

**Comment by bogiton** [comment]
I can't access it either. Nothing under releases/tags too.

**Comment by iceman1001** [comment]
ok.  so I need to add you as admin...

**Comment by iceman1001** [comment]
So,  @bogiton   you can see the draft.  
Question,   where are we in this process?   What more do we need to fix before we can make the first release?

**Comment by bogiton** [comment]
I just did some last minute testing and I think we are ready to make the first release!
RSSI still does not work, but I don't think that is very important at the moment.
As soon as we make the first working release, we can focus on the optimization of the mifare classic emulation.

**Comment by iceman1001** [comment]
Since you fixed most things,  would you mind editing the draft-message,  in order to describe this first release the best?

**Comment by bogiton** [comment]
I'm not considered very good in describing, but I gave it a try. Do you think we should also refer to the supported configurations/modes?

**Comment by iceman1001** [comment]
Execellent
and yes,  I do think we should write that in order to spread information and knowledge.

**Comment by iceman1001** [comment]
I removed this section since it is more for our roadmap here,  than for a release note.

_Next releases would probably deviate from the old firmware and try to get closer to the RevG functionality and features, without losing though the usability of the rebooted device._

**Comment by bogiton** [comment]
Indeed, I think it's better now.

**Comment by iceman1001** [comment]
and its live!

https://github.com/iceman1001/ChameleonMini-rebooted/releases/tag/v1.0

Great work!

**Comment by bogiton** [comment]
Cool :)
