### ISSUE TITLE
Sniffing All Data

### ISSUE THREAD

**Issue by ghost** [iceman1001/ChameleonMini-rebooted#193]
Hi.
I have a mifare-classic card(SAK=08,ATQA=0004). But it ​can't be cracked by mfoc or mfcuk, because the bug has been fixed by a Chinese manufacturer. I used the Chameleon to sniff the password, but some passwords are still unknown.

Is it possible to sniff all the communication between the reader and the card and send it through the serial port? So that I can get all passwords of the card. 

I know PM3 can do it, but I don't have enough money.

Now I have a PN532 reader ,a RC522 (with Arduino, act as a reader) and a Chameleon RevE.

**Comment by iceman1001** [comment]
User question,  not relevant to source code issue.
