### ISSUE TITLE
IM GOING TO FUCKING LOSE IT 

### ISSUE THREAD

**Issue by bjenky** [iceman1001/ChameleonMini-rebooted#195]
THIS IS UNREASONABLY COMPLICATED 
WILL SOMEONE (ICEMAN) FUCKING HELP ME PLEASE BEFORE I FUCKING JUMP OFF A BRIDGE?

I WILL PAY FOR IT AT THIS POINT JESUS
WHY IS THIS SO FUCKING DIFFICULT??/?
FML THIS IS SOME ELITIST BULLSHIT
WHO WANTS TO MAKE 50$?!!!
1/2 UP FRONT HALF WHEN YOU SUCCESSFULLY HELP ME GET MY MINI WORKING!!!
PLEASE BEFORE I TRULY GO INSANE

**Comment by bjenky** [comment]
I HATE THIS SHIT

**Comment by iceman1001** [comment]
Manners maketh man.

This is inappropriate.   Find your way to the discord server and ask questions / ask for help.
