### ISSUE TITLE
build failure.

### ISSUE THREAD

**Issue by iceman1001** [iceman1001/ChameleonMini-rebooted#2]
Getting the project to build.

user@ubuntu:~/ChameleonMini-rebooted/Firmware/Chameleon-Mini$ make
Makefile:120: ../LUFA/Build/lufa_core.mk: No such file or directory
Makefile:121: ../LUFA/Build/lufa_sources.mk: No such file or directory
Makefile:122: ../LUFA/Build/lufa_build.mk: No such file or directory
Makefile:123: ../LUFA/Build/lufa_cppcheck.mk: No such file or directory
make: *** No rule to make target '../LUFA/Build/lufa_cppcheck.mk'.  Stop.

**Comment by bogiton** [comment]
Maybe try and get them from: https://github.com/abcminiuser/lufa/tree/master/LUFA/Build ?

**Comment by ceres-c** [comment]
Trying to fix it, initial commit on my fork. Still not compiling and complaining about the avr/io.h header file, which seem to be a device-specific file

--Edit--
Ok, my bad, I needed another couple of dependencies
You'll need to `apt-get install gcc-avr avr-libc binutils-avr`

**Comment by iceman1001** [comment]
Nice one, bro!  
I got rid of some warnings too.

**Comment by ceres-c** [comment]
I'm working on getting it to compile, but I've got a doubt. Given we're working with a chinese codebase different from the original one and quite messy (we've been given a codebase not compiling and that's enough), I don't know what to do.
The file AntennaLevel.c is missing and AntennaLevel.h is quite similar but our version miss 2 functions which are present in the main repo, naming
```
void AntennaLevelTick(void);
void AntennaLevelResetMaxRssi(void);
```

Now, should I copy-paste (brutal, I know) the official AntennaLevel.c and update AntennaLevel.h accordingly or should I strip out unused functions from the c file?

**Comment by iceman1001** [comment]
Go nuts,   I already did merging with revG,  as mentioned in issue 3 ...     Mea culpa.

This codebase is old,  so first I tried to get official revE merged,  and  thought that the changes should be easy to spot the difference but they were plenty.   

So either we go nuts or we start over from scratch,  merging offical revE with latest fixes on to this one.
What do you think?

**Comment by ceres-c** [comment]
Kinda hard to decide, that's why I asked. We might go for the easy way and hack it together, but it might make thing way worse later. Actually I have no idea how the chinese managed to use this, given how many errors there were just for compiling...

BTW, funny thing: I don't own the original chamelon, nor this one. Just doing it for fun, but I can't test anything. Hehe

**Comment by iceman1001** [comment]
The biggest advantage is the GUI and the reader-attack for mifare classic. 
and eight leds.  ...  lets go nuts and hack it up :)

We can always start fresh from the original codebase with all we learned from this practice.

No chameleon?!?  And you call yourself a pentester ?  ;)  just kidding.  Its chrismas soon!

**Comment by ceres-c** [comment]
So we're going to hack our way into new features. This is going to be fun to watch :-D

Yeah, this Christmas I'll gift myself some stuff, you bet it ;-) I had a 180$+ cart on rfxsecure, that was only tags eheheh... Still I believe I'll go for the official version with chameleon

**Comment by ceres-c** [comment]
Also, @iceman1001, do you have keybase or something like that so I can contact you via chat? That'd be helpful given I don't have a chameleon to use for tests and I'd do with some more information in order to work on this :-/

**Comment by iceman1001** [comment]
It took some years before I got one aswell.  Wanted to know what the fuzz was about. 
Signal?  irc?  open thread on forum?

**Comment by ceres-c** [comment]
Yeah, I got into RFID quite late... I'm no Major Malfunction, after all

I'd go with signal given I already have it installed on my phone and I don't have an IRC client to use "on the go". Won't spam you, I promise. Also, the forun doesn't seem too suit given I might have to ask you info to understand this program but mostli non-technical stuff which isn't worth getting everybody an alert ;)

**Comment by ghost** [comment]
I'm new into NFC, but like reversing etc.
I have an original chameleonmini revG.
Next investment will be a Proxmark3.
Mabe I can contribute with some Infos or check out the GUI

**Comment by iceman1001** [comment]
Go for it!  I just want this project to compile as-is now.

**Comment by iceman1001** [comment]
Yes!   It compiles!    Woop!
