### ISSUE TITLE
Chameleon mini Chinese version

### ISSUE THREAD

**Issue by nurzhannn** [iceman1001/ChameleonMini-rebooted#21]
Chameleon mini Chinese version will not work with the original firmware because the Chinese version this not original microcontroller atxmega128a4u,replaced by atxmega32a4u

original firmware gets out error:
avrdude: ERROR: address 0x9010 out of range at line

<<< https://github.com/iceman1001/ChameleonMini-rebooted >>> the Chinese gave the distorted firmware,computer does not see Chameleon-mini
need something to fix it in the firmware
someone have a working firmware ?

**Comment by WolfgangMau** [comment]
[ChameleonMiniRDV2.0_ATxmega32A4U](https://github.com/iceman1001/ChameleonMini-rebooted/blob/master/Firmware/Compiled/ChameleonMiniRDV2.0_ATxmega32A4U.hex)
this one works at least partially
(no Mifare Ultralight, Random-ID and possibly no 'Reader' - at least on my side)
look at
[issue #11](https://github.com/iceman1001/ChameleonMini-rebooted/issues/11)

**Comment by nurzhannn** [comment]
Thank you,what software are you using and driver ?
if fix the second firmware, other cards will work ?

**Comment by WolfgangMau** [comment]
can only tell about  how I got it flashed on windows7

Drivers:
[LUFA-Driver](https://github.com/iceman1001/ChameleonMini-rebooted/tree/master/Drivers/LUFA%20Driver) for CDC Mode (normal mode)

DFU-Driver for uploading (bootloader mode)
on Windows7 I installed the driver from within [this zip](https://github.com/iceman1001/ChameleonMini-rebooted/blob/master/Software/Win32/dfu-programmer-win-0.7.2.zip) 

ah yeah, I renamed the files  ... but you can read about that in my post on issue #11 
Software:
normal mode (Configuration): [Chameleon%20Mini%20RevE%20Rebooted_en](https://github.com/iceman1001/ChameleonMini-rebooted/blob/master/Software/Win32/Chameleon%20Mini%20RevE%20Rebooted_en.exe) 

in order to flash I needed to copy the [BOOT_LOADER_EXE](https://github.com/iceman1001/ChameleonMini-rebooted/blob/master/Software/Win32/BOOT_LOADER_EXE.exe) next to the [FlashTools](https://github.com/iceman1001/ChameleonMini-rebooted/tree/master/Software/FlashTools) and find me a working msvcr120.dll ... i guess thats all, but maybe I forgot something ;-)
the rest can be read in issue #11

may all be different on other windows-versions
I'm not a fan of windows, so not much experience here 
but I did not got it working on OSX for now

**Comment by nurzhannn** [comment]
https://github.com/iceman1001/ChameleonMini-rebooted/tree/master/Drivers/LUFA%20Driver
 how did you install ?
I only have a microcontroller driver installed

**Comment by bogiton** [comment]
https://github.com/iceman1001/ChameleonMini-rebooted/wiki/Flashing---windows
This info doesn't help?

**Comment by iceman1001** [comment]
To be correct,  you need to find the msvcr12 compiled with debug info.  Hence the ending **d** in the filename  **msvcr120d.dll**.     It is usually found with a visual studio download.

I added one to the folder:
https://github.com/iceman1001/ChameleonMini-rebooted/tree/master/Software/FlashTools

The BOOT_LOADER_EXE should also been there when running it.

The two existing "reset" firmware files (under Compiled folder)

1. ChameleonMiniRDV2.0_ATxmega32A4U     (resets to basic function)
2. ITS_A_CARD.hex    (restore back original chameleon mini rebooted function)

**Recovery process:** 
If you screwed up your device,  flash 1,  then flash 2 with BOOT_LOADER_EXE.
if you not screwed up your deivce,   flash 2 with BOOT_LOADER_EXE.

**Comment by WolfgangMau** [comment]
my original chameleon was able to emulate ultralight, was able to create random mf uids and mf-detection ... but after flashing the both files it can only emulate mf (1k & 4K)
so it's far away from 'restore back original chameleon mini rebooted function'

so what did I wrong?
I would like to have the 'original chameleon mini rebooted function'

btw: on my virgin windows7 the msvcr120d.dll was not enough I needed the msvcr120.dll too
otherwise I got an error like 'msvcr120.dll is missing'

ok, random mf-id seems to work again, but mfu still doesn't work .. and to be honest .. I don't know if Detection works before ;-)

**Comment by bogiton** [comment]
As far as I remember there was no reader configuration in my original firmware.
In any case, the official stock binaries can be found here: https://github.com/iceman1001/ChameleonMini-rebooted/files/1573135/bootloader-files.zip
which you can flash using the https://github.com/iceman1001/ChameleonMini-rebooted/raw/master/Software/Win32/BOOT_LOADER_EXE.exe

**Comment by iceman1001** [comment]
When you run **VERSIONMY?**  in a terminal session,   it says?

If you could act as READER,  then you must have used Chameleon Mini RevG firmware.  Which device do you have?  

Hold on,  how did you to that "files/"  link?!?  Where do I see those zip-files?!?  Is that some GitHub woodoo I haven't seen yet?

**Comment by bogiton** [comment]
hahaha, it is from a comment of mine in issue 11 :P
https://github.com/iceman1001/ChameleonMini-rebooted/issues/11#issuecomment-352876568
Actually these are the files that were provided by the shop I got my device from (along with the BOOT_LOADER_EXE and the original GUI).

**Comment by iceman1001** [comment]
Aha,  well,  we have **two bin files** which should be original.  
Then we have a few **ITS_A_CARD.hex** which should be original aswell..
at last we have  **ChameleonMiniRDV2.0_ATxmega32A4U**  which is to put it in basic bootload-mode.

So @WolfgangMau   I believe you should be able to get to square one again.

**Comment by WolfgangMau** [comment]
@iceman1001 
with
ChameleonMiniRDV2.0_ATxmega32A4U
ITS_A_CARD.hex

VERSIONMY?
101:OK WITH TEXT
Chameleon-new-1.0

with your files
VERSIONMY?
101:OK WITH TEXT
Chameleon-new-1.0

but .... mfu works again - YEAH!

your files have different size than my generated myfile.bin and myfileee.bin
your myfile.bin  -> 23KB . (mine -> 23KB)
your myfileee.bin -> 23B (mine -> 4KB)

**Comment by iceman1001** [comment]
firmware **myfile.bin** should be less than 32kb (otherwise it will not fit the device)
eeprom file  **myfilee.bin** should only be around 40bytes.

**Comment by iceman1001** [comment]
I would say your **myfilee.bin** was causing some troubles.
You can bin-diff them

**Comment by WolfgangMau** [comment]
thx very much for the files ... I'm working in Finland this week ... but I carried the pm3 and the cmr with me because I was hoping that I get that fixed somehow over this week ... finally it worked out just the second day - very big thanks to you guys @iceman1001  & @bogiton

**Comment by iceman1001** [comment]
Well, we are happy aswell.   At least we have the option to fiddle with the firmware and make a better GUI now.  We are all learning how to play with this device. 

How is it going for @nurzhannn  ?   Have you also got your mini up again?

**Comment by nurzhannn** [comment]
1. ChameleonMiniRDV2.0_ATxmega32A4U (resets to basic function)
2. ITS_A_CARD.hex (restore back original chameleon mini rebooted function)

flash two firmwares and later i read microcontroller:
[1.txt](https://github.com/iceman1001/ChameleonMini-rebooted/files/1633496/1.txt)
computer does not see nothing 

then checked these two files:
[myfile.bin.txt](https://github.com/iceman1001/ChameleonMini-rebooted/files/1633544/myfile.bin.txt)
[myfilee.bin.txt](https://github.com/iceman1001/ChameleonMini-rebooted/files/1633547/myfilee.bin.txt)
not working the lights are on but computer does not see

**Comment by bogiton** [comment]
What is with the ".txt" extension? The myfile and myfilee files should have the ".bin" extension only.
Are you sure your device is in bootloader mode?
What is the output of the BOOT_LOADER_EXE.exe when you run it?
There is a different procedure for the hex/eep files (that are created from compiling the code) and the pre-compiled .bin files.
For the latter, I believe, that the guide [Flashing windows](https://github.com/iceman1001/ChameleonMini-rebooted/wiki/Flashing---windows) is very thorough and should suffice.
As for the hex/eep files there is the flash.bat script (as well as the rest of the needed files) located in [FlashTools](https://github.com/iceman1001/ChameleonMini-rebooted/tree/master/Software/FlashTools).

**Comment by nurzhannn** [comment]
First a microcontroller memory was erased and next i download firmware:
1.ChameleonMiniRDV2.0_ATxmega32A4U.hex
bootloader "ATXMEGA32a4U"  is was installed:
https://github.com/iceman1001/ChameleonMini-rebooted/tree/master/Drivers/DFU%20Driver
computer identified "atxmega32a4u".

Next I did everything according to the instructions: https://github.com/iceman1001/ChameleonMini-rebooted/wiki/Flashing---windows
in "DEVICE MANAGER" There is nothing,zero reaction when I connect "Chameleon-mini"

myfile.bin should be the size of 32KB,true ?

**Comment by bogiton** [comment]
Let's try this again.
Hold down the black button and then connect your device via USB in a windows PC. This should put the Chameleon in bootloader mode and you should be able to see it as "atxmega32a4u" in the device manager.
Next, put the following files in the same directory:
* myfile.bin
* myfilee.bin
* BOOT_LOADER_EXE.exe

And then run the BOOT_LOADER_EXE.exe.
What is the output of the cmd window?

**Comment by nurzhannn** [comment]
old_driver_bootloader
Erasing flash...  Success
Checking memory from 0x0 to 0x6FFF...  Empty.
0%                            100%  Programming 0x20 bytes...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]  Success
0%                            100%  Reading 0x400 bytes...
0%                            100%  Programming 0x5B00 bytes...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]  Success
0%                            100%  Reading 0x7000 bytes...
load_success!

**Comment by iceman1001** [comment]
prefect!    Time to close this issue

**Comment by nurzhannn** [comment]
in "DEVICE MANAGER" There is nothing,zero reaction when I connect "Chameleon-mini"
computer not does see

**Comment by iceman1001** [comment]
have you installed the chameleon mini usb drivers?  Are there a new usb-device assigned to a comport?

**Comment by nurzhannn** [comment]
how installed the chameleon mini usb drivers if computer not does see "chameleon-mini" ?

**Comment by iceman1001** [comment]
read my previous answer.

**Comment by nurzhannn** [comment]
new usb-device,no nothing

**Comment by iceman1001** [comment]
unplug,  plug in,   no new usb device when looking in DeviceManager?

**Comment by nurzhannn** [comment]
no

**Comment by iceman1001** [comment]
I can't help you. I have no idea why your computer doesn't identify it.

**Comment by nurzhannn** [comment]
Checking memory from 0x0 to 0x6FFF...  Empty.
0%                            100%  Programming 0x60 bytes...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]  Success
0%                            100%  Reading 0x400 bytes...
0%                            100%  Programming 0x100 bytes...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]  Success
0%                            100%  Reading 0x7000 bytes...
load_success!

Programming 0x60 bytes instead Programming 0x20 bytes
Programming 0x100 bytes instead Programming 0x5B00 bytes

**Comment by nurzhannn** [comment]
"myfile.bin" and "myfilee.bin" size 1 kb for both

**Comment by iceman1001** [comment]
Which bin-files are you using?  That is wrong sizes.
Did you use:   https://github.com/iceman1001/ChameleonMini-rebooted/files/1573135/bootloader-files.zip

Put those 2 bin files inside same folder as BOOT_LOADER_EXE.exe file.   
run BOOT_LOADER_EXE.exe

What is the output for that?

**Comment by jackkleeman** [comment]
I can't get BOOT_LOADER_EXE.exe to work as dfu-programmer doesn't work on my pc, only on my mac. Can you tell me the equivalent dfu-programmer instructions? I try erase but it tried to erase much more than to 0x6FFF, and the erase fails at 0x7FF1

**Comment by jackkleeman** [comment]
I have same issue btw, unrecognised except in bootloader

**Comment by nurzhannn** [comment]
Thank you for your patience, everything is working!

**Comment by iceman1001** [comment]
@nurzhannn   great!
@jackkleeman  what is the output from your BOOT_LOADER_EXE ?  (with correct bin-files in the same folder)

**Comment by jackkleeman** [comment]
old_driver_bootloader
dfu-old-driver: no device present.

dfu-programmer also doesn't work. this is on my pc. On my mac it does work but it doesnt seem to erase or flash correctly.

**Comment by bogiton** [comment]
not in bootloader mode then.

**Comment by jackkleeman** [comment]
It is definitely in bootloader mode and it works on my mac

**Comment by iceman1001** [comment]
indeed,  have you put it in bootloader_mode?  
Like the instructions on Wiki https://github.com/iceman1001/ChameleonMini-rebooted/wiki/Flashing---windows states?

**Comment by jackkleeman** [comment]
yes, and device manager sees it correctly

**Comment by iceman1001** [comment]
You see **Atmel Usb Devices ATxmega32A4U** in device manager?

**Comment by jackkleeman** [comment]
I see ATxmega32A4U and in properties the device type is Atmel USB Devices

**Comment by iceman1001** [comment]
The dfu-programmer doesn't work.  

You must use BOOT_LOADER_EXE or AVR-mkII device to flash. 
which OS are you on?  Something is off here.  If the device is identified as ATxmega32A4U the BOOT_LOADER_EXE will find it...  
Possible,  that the device is not in bootloader mode,  you may have installed wrong drivers,  since you need two of them..

**Comment by jackkleeman** [comment]
I am trying this on PC. Dfu-programmer works on mac so it is definitely in bootloader. I installed the dfu driver in this repo. Do I need any other driver for talking to bootloader?
My AVRISP is in the mail; I hope that can fix this

**Comment by iceman1001** [comment]
dfu-programmer works on mac, ok, what is the output from that one?  Im curious.

You need two drivers on PC,  so the device gets identifed correct in the two modes.
I have no idea it is on OSX.

**Comment by jackkleeman** [comment]
I can't get recognised in LUFA mode right now.
`➜  Compiled git:(master) ✗ dfu-programmer atxmega32a4u erase            
Checking memory from 0x0 to 0x7FFF...  Not blank at 0x7FF1.
Erasing flash...  Success
Checking memory from 0x0 to 0x7FFF...  Not blank at 0x7FF1.`

**Comment by iceman1001** [comment]
that is only the **erase** command.  Didn't you run the rest?

**Comment by jackkleeman** [comment]
Yes. 
`➜  Compiled git:(master) ✗ sudo dfu-programmer atxmega32a4u flash ITS_A_CARD.hex
Checking memory from 0x0 to 0x58FF...  Empty.
0%                            100%  Programming 0x5900 bytes...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]  Success
0%                            100%  Reading 0x8000 bytes...
[ X  ERROR
Memory read error, use debug for more info.
FAIL
Memory did not validate. Did you erase?`

After this the lights can come on in LUFA mode but its not recognised by mac or pc and the button doesnt move the light.

I tried my own compiled ITS_A_CARD and it didn't work.

**Comment by iceman1001** [comment]
that doesn't look like your flash worked.
Did you try the ITS_A_CARD.hex that comes with this repo?

**Comment by jackkleeman** [comment]
Yup

**Comment by iceman1001** [comment]
What is the output from dfu-programer with the original hex?

**Comment by jackkleeman** [comment]
That was the original hex. I was saying I also tried my compiled one.

**Comment by bogiton** [comment]
dfu-programmer shows the exact same (erroneous) output in windows, where it also does not work.
As iceman mentioned earlier, the only two methods to flash the rebooted device are either using BOOT_LOADER_EXE in windows (with the .bin files) or the AVR-mkII device.

**Comment by jackkleeman** [comment]
Ok I will try another computer. Thanks

**Comment by jackkleeman** [comment]
I have the same issue on another computer. No worries as my AVR-mkII is en route. However I think this project really needs another solution! Do we have a way to reverse engineer the bootloader exe?

**Comment by iceman1001** [comment]
Feel free to figure out what the BOOT_LOADER_EXE.exe / createbin.exe does.  I'm guessing it has a old dfu-programmer inside together with the aes encryption.  There is more info in the other issues or wiki.

Getting flash working for other than windows users would be great.

**Comment by Skydev0h** [comment]
BOOT_LOADER_EXEC seems to (at least) use some library like https://github.com/dfu-programmer/dfu-programmer judging from some stuff in decompiled code:

![image](https://user-images.githubusercontent.com/5331782/40517822-093a3c9e-5fc0-11e8-8d5e-717b8ba5268f.png)

![image](https://user-images.githubusercontent.com/5331782/40517836-1700610a-5fc0-11e8-9f68-c340ffb3b36b.png)

![image](https://user-images.githubusercontent.com/5331782/40517847-211e3d1a-5fc0-11e8-903c-d5a80626a13f.png)

That stuff looks VERY much like the following file:
https://github.com/dfu-programmer/dfu-programmer/blob/master/src/commands.c

And the main itself looks very much like the main of that dfu-programmer:
![image](https://user-images.githubusercontent.com/5331782/40518556-ec3affee-5fc3-11e8-8c32-89595709c5ea.png)

Createfile does not seem to use AES encryption, but it does much juggling and xoring with data (may be some standard algorithm or may be homebrew one):

![image](https://user-images.githubusercontent.com/5331782/40518601-2876d208-5fc4-11e8-89f5-960adf433d35.png)

![image](https://user-images.githubusercontent.com/5331782/40518622-3df16ff8-5fc4-11e8-8525-8f7fc1feef7f.png)

**Comment by bogiton** [comment]
Indeed, the BOOT_LOADER_EXE has bundled a possibly modified dfu-programmer. All the output text of the command window seem to match the dfu-programmer. Maybe to also set the fuses through that?

**Comment by securechicken** [comment]
@iceman1001 to be closed now we have a proper Linux, OSX and Windows way to flash. And also because more than 1 year passed :)

**Comment by iceman1001** [comment]
@Skydev0h  you should have chatted with @slurdge   ... he figured things out aswell

**Comment by ghost** [comment]
Hello, im sorry if im bringing back this again, since i'm so confuse, the chameleon wont to bootloader mode, been holding black button before and after plug in cable, seems not work, is there any way to make and force my chameleon mini to bootloader mode? 

the goal is just to update firmware to current release.

```
--> VERSION?
101:OK WITH TEXT
Chameleon-Mini 150304 using LUFA 130901 compiled with AVR-GCC 4.8.1

--> MEMSIZE?
101:OK WITH TEXT
1024

--> config?
101:OK WITH TEXT
MF_CLASSIC_1K
```

driver installed :
![image](https://user-images.githubusercontent.com/37841938/63336659-b8beb880-c369-11e9-882a-5b5678b1e802.png)

device i bought from :
https://www.aliexpress.com/item/32990434650.html?

**Comment by iceman1001** [comment]
@shinhub  That version string is way too long.   I think limit is 32bytes....  What happend here.

**Comment by iceman1001** [comment]
And that version string doesn't look like its a RevE rebooted firmware either.  
That ad claims own firmware,..   So sorry,   we can help you.  You will need to ask the seller about it.

**Comment by Akisame-AI** [comment]
Sorry for playing the necromancer here but does the Chinese version or the original chameleon mini revE have JTAG support?

If so you could just remove the atxmega32a4u with a 6 dollar atxmega128a4u.
It is surprisingly easy to do. Especially with such a big chip as the atxmega. 

Can someone confirm that this is a viable strategy. If so I might buy the Chinese version since I am mainly going to use it to hobby around a bit and I am less worried about breaking a 35 dollar version than I am a 150 dollar version

**Comment by slurdge** [comment]
Yes you can manually reflash the chip if you have the needed tools. However I'm not sure that the firmware is compatible, especially concerning the flash. Why would you need the 128 version? There's quite a bit of optimization in software you can do before changing hardware.

**Comment by Akisame-AI** [comment]
well. I have a atxmega128a4u in my drawer that is not being used at the moment and there is a big difference between the 32kb and 128kb version of the atxmega microchip. The biggest differences are in the SRAM and EEPROM (2x as much for both). Both of which would come in handy when I am programming a lot on there myself.
But I just looked up the schematics of the original revE and it also uses an atxmega32a4u chip and they upgraded to the 128kb version for the revG.

**Comment by iceman1001** [comment]
Feel free to make a mcu transplant and do tell us how it went and what you did to make the firmware work on your new setup.

**Comment by Akisame-AI** [comment]
I'll check how it functions with the 32kb version and if I am unsatisfied I will install the 128kb version and see if I can get the firmware to work. If not I will have to resolder the 32kb version...

Edit: Ordered a Chameleon tiny as well as the chinese mini revE version. Decided that I can fiddle around on the chinese version with the hardware and keep the tiny working properly
