### ISSUE TITLE
draft for release v1.1

### ISSUE THREAD

**Issue by iceman1001** [iceman1001/ChameleonMini-rebooted#23]
With this draft I open up for discussions about which functionality the next release should have.

Current firmware works with existing GUI.  As of this release we are free to deviate from old legacy and bring new/fixs  into action!

### original idea
-  merge **MF_DETECTION** functionality into **MIFARE_CLASSIC_nK** ,  partly to save space and since it really doesn't need its own function.
- **MF_CLASSIC 1K**  should not react to magic command default.  It should be an option.
- **MF_CLASSIC 1K**  SAK 0x08  - 0x88  ,  optional to set SAK ,  not to be read for Sector0-Block0.
- **MF_CLASSIC 1K**  crypto1 enhancements.
- tag slots,  only allow two slots to have 4K support,  in order to save memory

### What currently is implemented
- **firmware naming** a new firmware name to better indicate which version
- **MF_CLASSIC 1K**  should not react to magic command default.   Compiler-directive
- **MF_CLASSIC 1K**  optional ATQA/SAK.  Can be set per slot individually
- **MF_CLASSIC 1K**  crypto1 enhancements.
- tag slots,  only allow two slots to have 4K support,  in order to save memory

**Comment by kevin2008-01** [comment]
waouuu! fine. thank you iceman1001

**Comment by iceman1001** [comment]
@bogiton 
So what do you think?

**Comment by bogiton** [comment]
Should we also remove the "MY" extension for this release?
Are there 2 slots that support 4K? I thought it was only the first one.

**Comment by iceman1001** [comment]
Should be one,   but all this extra memory we now have...  Question is if we should be able to do 4k everywhere..
4*8kb in flash mem
and the active slot is downloaded to ram ?
..
but when to save the potential changes made by reader to flashmem?
and the powerdown...

**Comment by bogiton** [comment]
That needs some thought. And definitely some testing.
