### ISSUE TITLE
Provide Precompiled Hex/Bin

### ISSUE THREAD

**Issue by WolfgangMau** [iceman1001/ChameleonMini-rebooted#24]
would it be possible to provide compiled Versions of the Chameleon-Mini.hex/Chameleon-Mini.eep to the releases?
Since at least for me, using OSX, the compiled files seems not to work (even if flashed with windooze) 
there are no errors while compiling, so it's kinda hard to figure out the problem (at least for me/ for now)
btw: if I compile the RevG firmware on OSX -> it works (on my RevG)

**Comment by bogiton** [comment]
There shouldn't be any difference of the produced hex/eep files after re-compiling the code. So I'm not sure if there is a point to also provide those.
On the other hand, we could include the bin files (after running createbin in windows), but then again, you also have to be on windows to flash those with the BOOT_LOADER_EXE.

**Comment by WolfgangMau** [comment]
it's not the problem that I have to use windows to get them on the chameleon, it's more about that the files I compile on osx did not work like expected.
Therefor it would be nice to have files that work for sure and which I can compare/diff my files against. 
If you would like to compare, here are my compiled hex & eep: https://ufile.io/p2evx
if I use the flash.bat - the chameleon could not be read/edited from the gui
but I can connect via socat from osx
and if I configure a slot  (mf_1k per example) it can also be read by pm3 ... so mostly 
it works ... but something is different because the gui does not work anymore
If I flash the chamelon with the myfile.bin & myfilee.bin (via BOOT_LOADER_EXE), whicht I got from iceman last week, all works fine.
but I then all slots have being set Mode to 'CLOSE' 
it's not really a problem, since I can configure it via terminal ... but would be nicer i the gui works also ... and since the gui it should work (so mentioned in the release notes) there must be some little difference between my and other hex/bin

**Comment by kgamecarter** [comment]
You can enable WSL and install ubuntu in Windows 10.
Compile work fine.

**Comment by stek29** [comment]
They're now available on Releases page.

**Comment by iceman1001** [comment]
time to close this one.
