### ISSUE TITLE
Ultralight PWD logging

### ISSUE THREAD

**Issue by iceman1001** [iceman1001/ChameleonMini-rebooted#26]
Tested successfully to implement the logging of Ul-Ev1 pwds..

![capture](https://user-images.githubusercontent.com/8577004/35303201-6ad73648-0091-11e8-9b0f-04a1711df79d.PNG)

**Comment by bogiton** [comment]
Awesome! :)

**Comment by iceman1001** [comment]
its pushed :)  Thanks @bogiton !

**Comment by bogiton** [comment]
We all thank you :)

**Comment by kevin2008-01** [comment]
ah... implemented ? see you!
