### ISSUE TITLE
DEFAULT_BUTTON_LONG is not defined in Makefile or SETTINGS

### ISSUE THREAD

**Issue by prensel** [iceman1001/ChameleonMini-rebooted#30]
DEFAULT_BUTTON_LONG is not defined and causing an error.
Add this in Makefile and it will compile
SETTINGS += DEFAULT_BUTTON_LONG=BUTTON_ACTION_CYCLE_SETTINGS

**Comment by iceman1001** [comment]
make a PR!

**Comment by WolfgangMau** [comment]
to be correct ... you needd to add (at least on osx):
SETTINGS    += -DDEFAULT_BUTTON_LONG_ACTION
SETTINGS    += -DEFAULT_BUTTON_LONG_ACTION=BUTTON_ACTION_CYCLE_SETTINGS

**Comment by bogiton** [comment]
Ah right, I forgot about the Makefile. I only added it in the Atmel Studio project file :P

**Comment by iceman1001** [comment]
@bogiton   PR?

**Comment by bogiton** [comment]
I did commit to master :/ (sorry)

**Comment by iceman1001** [comment]
haha.  with powers comes responsibilities ;)
