### ISSUE TITLE
No serial output other then 200 from terminal ?

### ISSUE THREAD

**Issue by prensel** [iceman1001/ChameleonMini-rebooted#31]
I'm trying to use terminal access using putty but all i get is the 200:UNKOWN COMMAND response.
I cant even check what firmware currently there is on it because uploading any firmware other then supplied by lab401 doesnt work.
All information i have found sofar is rather incorrect or for the revG version (different mcu)
Ok it does work as it is but when theres no decent way to compile, upload and config any new firmware its saddly of no use actually...

**Comment by bogiton** [comment]
Maybe you are forgetting the "MY" extension of the commands for the rebooted version? It is HELPMY instead of HELP, VERSIONMY? instead of VERSION?, etc.
I believe that there is a good deal of information in our Wiki (https://github.com/iceman1001/ChameleonMini-rebooted/wiki). If some of it is incomplete as you say, please feel free to contribute.

**Comment by iceman1001** [comment]
And for putty to work,  you would also need to enable  "Local echo" in order to see what you write

**Comment by iceman1001** [comment]
The most of us here has successfully compile,  flashed and ran the chameleon revE with new GUI,  so your experiences differ quite a lot from us.

**Comment by WolfgangMau** [comment]
I can just compile the firmware, but it’s not running on the device (
compiled on os x & flashed with windooze flash.bat)
I can also only get the precompiled version to run ... even if the
compilation and flashing  throws no errors
<snipp>
edit: 
latest version works (compiled on osx & flashed on windows)

**Comment by iceman1001** [comment]
_most of us_

So you never got it to run?

**Comment by prensel** [comment]
Ok, great the suffix MY did certainly help ! But where is that mentioned ?
I'm currently writing a small howto and will post asap.
Compiling on Debian 9 just works fine but biggest issue now is that neither avrdude or dfu-programmer cant connect properly wit the mcu.

**Comment by iceman1001** [comment]
it was mentioned on the Wiki,  which I guess you didn't read before...

**Comment by prensel** [comment]
The wiki for the RevG ? 
Yes i read that one even printed Chameleon Command Structure as a guide..

**Comment by iceman1001** [comment]
No,  the wiki here where you posted, which is about the RevE rebooted version

**Comment by bogiton** [comment]
https://github.com/iceman1001/ChameleonMini-rebooted/wiki/Terminal-Commands
Here.

**Comment by prensel** [comment]
Ok i see it now. Never noticed that one because the GettingStarted link is pointing away from this site to the revG one... Maybe it's better to change that ?

**Comment by iceman1001** [comment]
true,  its taken from offical RevG,   I updated it to point to our wiki and be more clear.
