### ISSUE TITLE
Proposal of new firmware name: Chameleon-RevE instead of Chameleon-Mini

### ISSUE THREAD

**Issue by prensel** [iceman1001/ChameleonMini-rebooted#33]
Both RevG and RevE (our) versions of the Chameleon-Mini carry the same name for the firmware: Chameleon-Mini. 
Maybe it is an option to fork of our own name like Chameleon-RevE. I have created locally a new subdirectory under Firmware called Chameleon-RevE and changed all references for the 'old' name. Just in case everyone thinks this is a good idea, its ready for it :-)

**Comment by iceman1001** [comment]
Been talking about changing the firmware name reported and we decided to do that after release 1.
Which we now have,  however we haven't added anything to the firmware so no imminent release

**Comment by kevin2008-01** [comment]
And for sak 0x08 / 0x88 choice, any news iceman ?
