### ISSUE TITLE
Noob Walkthrough

### ISSUE THREAD

**Issue by riskydissonance** [iceman1001/ChameleonMini-rebooted#36]
Hi,

I'm pretty new to RFID testing, I've picked up a chameleon mini rebooted running **Chameleon-new-1.0** firmware from [lab401](https://lab401.com/products/chameleon-mini-reve-rebooted) and while it looks great, I'm struggling to get started on it.

I'm initially just looking to read Mifare Classic tags, but I'm only seeing commands for card emulation or reader attacks in [the commands](https://github.com/iceman1001/ChameleonMini-rebooted/wiki/Terminal-Commands) and "standard" chameleon guides obviously don't work for this firmware.

Could anyone help me with the fundamentals of this device? I'll be happy to write a noob walkthrough guide afterwards for the wiki and then [blog](https://jmpesp.me) about it.

Thanks,
RB

**Comment by kevin2008-01** [comment]
please test this GUI by iceman.
http://www.icesql.se/download/ChameleonMiniGUI/publish.htm
Upgrade firmware is not needed, use original firmware.
see you

**Comment by iceman1001** [comment]
The terminal commands is just terrible.  I never even consider using them, which is strange since I do love playing with proxmark3 client.  Use a GUI.  There are quite a few out there now, I guess it supports the idea that the terminal commands is hard to use.   You are most welcome to blog about GUI, terminal commands etc or feel free to update the wiki here.

**Comment by bogiton** [comment]
@robjbone Also bear in mind that the Chameleon-Mini rebooted is not suitable for reading tags, as iceman already mentioned in another issue. It can only be used for emulation.

**Comment by riskydissonance** [comment]
Thanks for the swift responses!

To check my understanding then, I'd clone tags using, for example, the proxmark, and then upload the dumps to the chameleon? I've checked out the GUI and doing that seems clear.

Other than that it can do reader attacks, but not just read tags directly? Would this be MF_DETECTION mode? I'm unsure as to how i'd do this using the GUI.

Thanks again.

**Comment by bogiton** [comment]
That is exactly right. Full dump of the tag using the proxmark and then emulate using the Chameleon. You would only need to convert between the proxmark dump format to the Chameleon one, before uploading the dump using the GUI.

About the reader attack, the steps are the following:
- Using the GUI set a slot to MF_DETECTION
- Approach the Chameleon to a MFC reader and let it work for a few seconds
- Back to the GUI, click on the mfkey32 button to start the cracking process

Hope that helps.

**Comment by iceman1001** [comment]
...yeah that converting of dumpfiles would be nice to some functionality in GUI...

**Comment by bogiton** [comment]
That's true. Especially since this is the usual workflow with our Chameleon. We have to think of a user-friendly way of converting. Maybe detecting the format somehow before the actual upload of the dump?

**Comment by kevin2008-01** [comment]
mf detect working only, if you have valid uid in chameleon and accepted by reader, guy....

**Comment by iceman1001** [comment]
yes, the reader must start a authentication in order for it to work..

and yes,  a user-friendly way of converting.. I already have some templates which shows a pm3 dump  or the offset for the special data in the beginning.

**Comment by dunderhay** [comment]
Hi there,

I noticed that the `identify` command has not been implemented and seems to be commented out in lines 275-281 of the terminal commands : https://github.com/iceman1001/ChameleonMini-rebooted/blob/master/Firmware/Chameleon-Mini/Terminal/CommandLine.c

```
  {
    .Command	= COMMAND_IDENTIFY_CARD,
    .ExecFunc 	= CommandExecIdentifyCard,
    .ExecParamFunc = NO_FUNCTION,
    .SetFunc 	= NO_FUNCTION,
    .GetFunc 	= NO_FUNCTION
  },
```
Is there a way to read the atqa, uid, and sak with identify command like Rev,G ?

Cheers in Advance

**Comment by iceman1001** [comment]
Apperantly there shouldn't be any reader functionality in RevE Rebooted,  only simulation,  hence all 14a-reader functionality in offical RevG is useless to us.

**Comment by Pilly170** [comment]
I have another noob question, If you choose the Random_UID on the button, how do you move to another tab.

**Comment by bogiton** [comment]
@Pilly170 You could set the Button Long function to SWITCHCARD to move to the next tag (by pressing the button for 1-2 sec).

**Comment by Pilly170** [comment]
@bogiton That option is greyed out for me, running W10 and latest gui download.

**Comment by iceman1001** [comment]
use the BUTTON dropdown instead...

**Comment by bogiton** [comment]
@Pilly170 or you have to flash a newer firmware :)

**Comment by Pilly170** [comment]
still ghosted, looks like i have firmware 1.0, are there any walkthroughs on how to flash? 
I also dont have the output view at the bottom, but then again Im running it on a VM and the res. maybe out.

**Comment by bogiton** [comment]
@Pilly170 I think this guide in our Wiki is clear enough: https://github.com/iceman1001/ChameleonMini-rebooted/wiki/Flashing---windows
On the Serial tab of the Chameleon GUI, is the BUTTON_LONGMY command there in the list when you connect your device?

**Comment by olaf1234** [comment]
Hello,
For Mf detection does it work with only UID1,UID2,UD3,BCC1 (Mifare ultralight). Can't upload the full UID (seems to be made for MF classic).  When I input the full UID it auto assign 11223344 UID.

**Comment by bogiton** [comment]
@olaf1234 MF_DETECTION is only applicable for Mifare Classic tags.

**Comment by olaf1234** [comment]
Ty for your anwser @bogiton 

One question lead to another:

Some context : When i'm reading my MF0ICU1 emulation  with my NFC taginfo app, the card UIDS,BBCS, OTP, LOCKBITs, DATA, manufacturer, RF technology, ATQA and SAK are identical to the real one. I uploaded on the chameleon a .bin file of my dump. Althought, even if the access conditions are read correctly (i got 3 read only pages), I can still modify them (include OTP and lock bits) with my MIFARE++ ultralight app. When i present my chamelon emulation to the real reader/writer : Incompatible card.

Questions: Does the state of my chameleon could be the problem(ex : IDLE, Halt)? , Does the real access conditions ( not the ones read) is noticed by the real reader/writer. Could it be something else? If those questions are valid interrogations(or not lol), can anyone give me some hints to resolve this? I'm pretty new to this.

**Comment by iceman1001** [comment]
Keep to subject.  Don't hijack issues.  Open a new issue related to the software.

**Comment by yaxax** [comment]
Can somebody explain to me about the reader attack chameleon mini reve.1 you select a slot.2 mf_detect.3 swichcards.4aply.5 then put the chameleon mini reve on the reader for a few seconds.is that the right way? And the uid function must be blank ?or ffffffff ?are with a valid uid?

**Comment by bogiton** [comment]
Hey @yaxax 
The MF_DETECTION configuration actually emulates a MiFare Classic 1k card against a valid reader.
Your steps seem correct. Set a slot to MF_DETECTION configuration, place it on the reader for a few seconds and then press the mfkey32 button on the Chameleon RevE rebooted GUI to retrieve the key.
As for the UID, it depends on the reader I guess, but it is more probable to work with a valid UID.

**Comment by iceman1001** [comment]
...but he would need to run the latest firmware from this repo,  or the default one...   and the latest GUI aswell...

**Comment by yaxax** [comment]
I have bought the chameleon mini reve at lab401 and have downloaded the gui 1.1.0.1 trough  their web and I also have the 1.2.0.18 iceman edition but can not read the output the  gui is bigger than my screen.And how can i put the info on a card like the video using a proxmark3?

**Comment by yaxax** [comment]
I allso have the chameleon mini app is that allso the latest version gui?And 1.1.0.1 is that allso the latest version gui

**Comment by iceman1001** [comment]
no... v1.2.0.18  is the latest

**Comment by yaxax** [comment]
I have the 1.2 .0.18 version but i can't see are read output.the gui is bigger then my screem I don't know how to explained this because I'm dutch and english is not so good but do you understand what I mean that I can read the output can you send me a link where the gui comes normaal on mij screem

**Comment by yaxax** [comment]
When I do mfkey do i get 32 numbers are 12 numbers ? im new in this just learning.

**Comment by iceman1001** [comment]
32numbers   ,  can you post the output?

**Comment by yaxax** [comment]
I try to send a pic but I don't know how?

**Comment by yaxax** [comment]
And the 32 numbers is that the block number 0?Are is it random block numbers?Because a block got 32 numbers right?

**Comment by yaxax** [comment]
![20190311_194123](https://user-images.githubusercontent.com/48149681/54186298-5d7bc680-44ab-11e9-8339-203038ae35a4.jpg)
`

**Comment by yaxax** [comment]
This I mean that I can't see the output off the gui on  my screem

**Comment by iceman1001** [comment]
Let me see if we can make the main window resizable..  @bogiton

**Comment by yaxax** [comment]
Ok thanks

**Comment by bogiton** [comment]
@iceman1001 yeah, I am on it. Gonna try a quick fix with scrollbars.

**Comment by iceman1001** [comment]
So Bogiton just added scrollbars,

**Comment by iceman1001** [comment]
And I just push out  v1.2.0.19,    So restart your gui and you should get the latest....

**Comment by yaxax** [comment]
![20190312_180126](https://user-images.githubusercontent.com/48149681/54220293-5d061e80-44f1-11e9-8119-feb905bb64a7.jpg)
Is still the same I can't read the output and the scrollbars don't work see foto

**Comment by iceman1001** [comment]
You need to resize the window...

**Comment by yaxax** [comment]
The gui still not working good see no output and I resize the window many time but still the same.But the older version works fine allso my other gui works fine.The latest gui most be fix.

**Comment by iceman1001** [comment]
your description of the problems lack details.  On my computer the GUI is resizable and when I do resize it I get scrollbars which lets me scroll down to the output window.    I can't verify your problems.

**Comment by yaxax** [comment]
I don't understand the output numbers i think keys?but i only see 12 numbers?instead of 32?
1 I put my uid in slot 1.2swichtcard.3aply.4 I disconnect the chameleon mini reve from the laptop and put it on the reader.
![20190312_201715](https://user-images.githubusercontent.com/48149681/54267601-d0537300-4579-11e9-8037-28c10d91ac9a.jpg)
This are the results when I put the chameleon mini reve on the reader .But I don't know how to go further.
![20190313_101821](https://user-images.githubusercontent.com/48149681/54267828-350ecd80-457a-11e9-95b5-e838da4792fb.jpg)And this is my card .

**Comment by ghost** [comment]
For me the GUI is working. And output is visible.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
An 13. März 2019, 10:25, yaxax schrieb:

**Comment by iceman1001** [comment]
When I look at the pictures,  the GUI is working well.  The output is visible.   

Given that the mfkey finds keys, I say that the firmware is working well.   So I suggest you google/youtube/read on pm3 wiki,  forum  to figure out what you need to do next.

**hint** yes those are keys...

**Comment by yaxax** [comment]
I search but I can't find nothing what I have to do futher.I allso read prox forum and github forum.but I can't find what I have to do next .i don't understand the output and how to go futher whit the output.

**Comment by yaxax** [comment]
And is the old version gui that's works fine but not the new version

**Comment by iceman1001** [comment]
This is not the place to discus that.  On Github issues we discus bugs/features in the code.

**Comment by yaxax** [comment]
But I talk about the chameleon reve I try to understand and learn my bad if I ask question that are related to the chameleon reve

**Comment by yaxax** [comment]
The chameleon-mini-reve-rebooted  where can I find some information  to understand the output info .I only see information about chameleon mini are g but not off reve.

**Comment by bogiton** [comment]
@yaxax The output is really straight-forward, if you know what you want to do. If you can't understand what "Key A" or "Key B" means, then you have to read the [datasheet](https://content.gototags.com/wp-content/uploads/Mifare_Classic_1K_MF1S503x.pdf) first. Also, since you have also a pm3, as far as I can see, you should be able to do what you probably need with that too... So, it's not a matter of Chameleon as a device at all.

**Comment by yaxax** [comment]
![20190313_143222](https://user-images.githubusercontent.com/48149681/54283378-263a1200-459e-11e9-8008-ed4f2f318c32.jpg)
Does this mean that I have to access cards because the red means access bites and I see 1 different access bites

**Comment by yaxax** [comment]
And I see 2 different access bytes I mean

**Comment by yaxax** [comment]
This is a better picture to understand what  I mean
![20190313_145209](https://user-images.githubusercontent.com/48149681/54284164-c17fb700-459f-11e9-865c-7e88757a5ca8.jpg)

**Comment by yaxax** [comment]
When I put my uid in the gui and then put the chameleon reve to the reader i got my own card information so do I must put my uid in the gui?1 slot 2 uid?3 swichcards. 4 aply 5 put to the reader right.?Because their is not so information I see video but this guy don't explain it good don't now wat he meaning and on the forum their allso nothing so can somebody help me out all what ask s related to the chameleon

**Comment by yaxax** [comment]
I try to learn but see no good info

**Comment by yaxax** [comment]
When i  put the uid number at section uid and then press apply then the uid goes back to ffffffff why is that something wrong with the software?

**Comment by bogiton** [comment]
Which UID are you trying to set? If the configuration is MF_CLASSIC then you have to enter a 4-byte UID (that is 8 hex digits). Usually, when the UID is of incorrect length it goes back to FFFFFFFF.

**Comment by yaxax** [comment]
Hi I try the uid off a ultralight card and then i put the 8 numbers off the ultralight card but then its set up to ffffffff again in the uid section when i do mf_detect.and whit 8 hex digits you mean the 8 numbers off the uid?

**Comment by yaxax** [comment]
Hi I try the uid off a ultralight card and then i put the 8 numbers off the ultralight card but then its set up to ffffffff again in the uid section when i do mf_detect.and whit 8 hex digits you mean the 8 numbers off the uid?

**Comment by bogiton** [comment]
@yaxax First set the configuration to MF_ULTRALIGHT and press apply. The UID should switch to a 7-byte one (14 hex digits). Then set the 7byte UID you want and press again the apply button. Although, I am sure that this can be done in a single step: set the configuration, set the UID and press apply.

**Comment by bogiton** [comment]
Also, MF_DETECT is for Mifare Classic 1K only. Not for Ultralight.

**Comment by yaxax** [comment]
Is their allso a way to detect ultralight?

**Comment by bogiton** [comment]
There is the PWD(MY) command. You set the configuration to ULEV1 for example and you try to authenticate with the reader. Then you run the PWD/PWDMY command to get the auth key that the reader issued.

**Comment by iceman1001** [comment]
The name is missleading.  It doesn't **detect** a tag.

**Comment by yaxax** [comment]
When I run the PWD are PWDMY command then I get 200:UNKNOW COMMAND.1 i set the configuration to MF_ULTRALIGHT.2 UID?3Button?And apply?And then put it to the reader and run PWD COMMAND and then PWD COMMAND?

**Comment by yaxax** [comment]
I still don't come out with key a and b.I read the data sheet a few times. When i got key a and b how do I put key a and b on a card. Because key a and b are always in the last sector of a block.

**Comment by bogiton** [comment]
I still don't know if you are trying to get the keys for mf classic or the key for ultralight.
`mf_detect` configuration enables you to get the key a/b for mf classic tags.
`pwdmy` (or `pwd` in the latest firmware) command enables you to read the stored auth password for ultralight tags (that support authentication).

**Comment by yaxax** [comment]
I try to get keys from mf classic 1k and allso  from ultralight.But i understand you now what you meaning thanks for your help your good.

**Comment by yaxax** [comment]
I still do not know how i should go further when I have key a & b in the output of the chameleon mini reve. I also have many times read the data sheet but understand a little bit of it because is in english and my english is not so good.   I still don't know how to put key & a & b on a card when I get key a&b from the chameleon mini reve.Can somebody help me out whit some advice .

**Comment by FabianAguinsaca** [comment]
> Todavía no sé si estás tratando de obtener las claves para mf classic o la clave para ultralight. 
> `mf_detect`la configuración le permite obtener la clave a / b para las etiquetas mf classic. 
> `pwdmy`(o `pwd`en el último firmware) el comando le permite leer la contraseña de autenticación almacenada para las etiquetas ultraligeras (que admiten la autenticación).

Sorry I'm new to the topic, I want to get the authentication password for a mifareultralingth, I have the cahamaleonmini rev e, but I can not establish the pwd command to know the password

**Comment by bogiton** [comment]
@FabianAguinsaca The scenario should be like this: First set a slot as an UL tag, with a UID that may be recognized by the reader. Then, present the Chameleon to the reader (with that slot active) and if the reader attempts an authentication against your emulated tag, the password would be saved in the Chameleon memory. Finally, when you connect your Chameleon back to your PC, you should be able to issue the PWD/PWDMY command in the Serial tab of the latest Chameleon Mini rebooted GUI and eventually retrieve the saved password.
