### ISSUE TITLE
anti copy,  Mifare Sector0 / block0 should be locked

### ISSUE THREAD

**Issue by kevin2008-01** [iceman1001/ChameleonMini-rebooted#38]
Now, new reader, fuck the chameleon, with anti-copy tag system.....
Please implement enable / disable fuid uid...for slot..... if is possible, right. ???
Thank you iceman1001.

**Comment by ceres-c** [comment]
I am not sure I understand what I'm reading...

**Comment by iceman1001** [comment]
Enable / Disable FUID ?   UID for slot..

I'm not sure either but that could be of the french way of expressing things.  There seem to be a wish for FUID to be optional per slot.   What I'm curious is what functionality FUID stands for?  use once?  magic? ...

**Comment by kevin2008-01** [comment]
Block 0 can only be written once.
    Even greater protection from a  system with "anti-clone" feature
    Use normal commands. eg. hf mf  wrbl 0 B FFFFFFFFFFFF a473f601200804006263646566676869
    Answers to chinese magic backdoor commands: NO

**Comment by iceman1001** [comment]
Hm,  this firmware as it is shouldn't allow for uid (block0) re-writing.  
it should set uid when we upload a dump etc.  Then it shouldn't allow at all for block0.

Aha, I see in the source code there is no limit for block0 writes.   ok.  Fair enough, I agree.

**Comment by ceres-c** [comment]
Now I get it and I agree

**Comment by kevin2008-01** [comment]
the reader must understand that writing block 0 is impossible, he must just read the chameleon. I do not know which command the reader sends to do the test or detect a tag copy. apparently, new readers are not blocked only in France, but also in other countries. see you

**Comment by quantum-x** [comment]
French readers implemented a 'magic check' where they send 0x43 0x40 to weed out magic tags.
However, the Chameleon Mini also has timing issues - which means they are often rejected by french readers. I'm assuming he's bumping up against problem 2 more than problem 1 - as the Chameleon should not respond to 0x43 0x40

**Comment by slurdge** [comment]
By "magic", you mean Chinese backdoor command ?

**Comment by quantum-x** [comment]
Correct.
Also - it seems that this behaviour has now been removed by default.

**Comment by securechicken** [comment]
@iceman1001 to be closed I think.

**Comment by iceman1001** [comment]
@shinhub  double check in code that block0 doesn't allow for Write commands...

**Comment by securechicken** [comment]
@iceman1001 you were right... I took quantum-x answer as clue of a previous patch.
I checked and found nothing in Mifare code to prevent Block0 write.
I am patching this.

**Comment by iceman1001** [comment]
keep in mind for your patch,  that the support-chinese-magic command macro defines,  at compilation time,  should allow for updating block0 etc..

**Comment by securechicken** [comment]
I swear won't hurt any chinese.

**Comment by iceman1001** [comment]
You do have a sense of humor.  Excellent.
