### ISSUE TITLE
UL Compat write incorrect behaviour

### ISSUE THREAD

**Issue by Skydev0h** [iceman1001/ChameleonMini-rebooted#40]
Ultralight compat write cmd expects data to be starting with third byte (idx 2) on second frame.
However, the specification states that data starts with first byte (D0) - possibly a copycat typo from write command.

![image](https://user-images.githubusercontent.com/5331782/40449325-dbe83fdc-5ee0-11e8-851a-9ccb7e448c00.png)

![image](https://user-images.githubusercontent.com/5331782/40449374-f5abc01a-5ee0-11e8-93be-e8c36f65b2db.png)

Maybe should change to Buffer[0]? 
Going to do some testing.

**Comment by iceman1001** [comment]
Great find!
I pushed a fix for it.   The compatbilty write must definitly use buffer0 and onwards
