### ISSUE TITLE
Memory overlap issue (first slot)

### ISSUE THREAD

**Issue by Skydev0h** [iceman1001/ChameleonMini-rebooted#41]
It seems that after commit https://github.com/iceman1001/ChameleonMini-rebooted/commit/459d9aa90e28eadab68d001c6b9aa4bed76bb1d8 there is memory overlap issue.

First, the code makes no sense: 
```	
if ( GlobalSettings.ActiveSetting == 0 )
		FlashAddress = Address + (uint16_t) GlobalSettings.ActiveSetting * MEMORY_SIZE_PER_SETTING_4K;
	else
		FlashAddress = Address + (uint16_t) GlobalSettings.ActiveSetting * MEMORY_SIZE_PER_SETTING_1K;
```

For the first case GlobalSettings.ActiveSetting is always zero.

Second, if the first slot uses 4K bytes (0..4095), then with this code second slot will clash into 1024..2047, third into 2048..3071 and fourth into 3072..4095, therefore writing to 4K slot 0 will damage/erase slots 1-3, and vice versa.

Logically correct way of determining address if you want first slot to be 4K and others to be 1K is:
```
if ( GlobalSettings.ActiveSetting == 0 )
		FlashAddress = Address;
	else
		FlashAddress = Address + MEMORY_SIZE_PER_SETTING_4K + ((uint16_t) GlobalSettings.ActiveSetting - 1) * MEMORY_SIZE_PER_SETTING_1K;
```

What do you think about it?
Same may apply to other functions like MemoryReadBlock, MemoryWriteBlock, MemoryClear.

By the way, what is the size of the SPI memory that we have?
I can't determine it by looking on chip because something is done with top of it (partially removed?)

Edit: I have clocked out 1F 24 00 00 from 0x9F opcode, which means we should have a AT45DB041D 4-Mbit (512 Kbyte!) chip.

**Comment by iceman1001** [comment]
several questions in one..
yes,  the 4k first slot limit overlaps the rest.  A change is needed indeed.
the flashmemory should be 32kb, so I don't understand your edited comment.  I see no reason for a manufacturer to lie about its actually bigger than it is..  Since that would have been a advantage.

**Comment by Skydev0h** [comment]
I could not find information about external flash size in the Internet, so i attempted to get the information from the chip directly. It may report density differently than standard code (however, 1F is manufacturer byte for Atmel, so that it may raise some questions). I will try to do out-of-bounds writes and reads and try to check for real capacity of chip. It may indeed be a "china version" of atmel chip that reports A but actually is B.

**Comment by Skydev0h** [comment]
Discussion about SPI memory size splitted to it's own thread: #42 
If all RevE-rb boards really have much more than 32KB ISP flash, that 4K-1K economy might be absolutely useless for the case.

**Comment by iceman1001** [comment]
@Skydev0h  are you doing a PR for the memory overlap?

**Comment by securechicken** [comment]
This seems to be still an issue (that I unfortunately just discovered #22).
At this point I do not understand how is 4k supposed to be handled in memory, and how is our "SPI" memory different than for RevG.
