### ISSUE TITLE
Graphic Design

### ISSUE THREAD

**Issue by nunojesus** [iceman1001/ChameleonMini-rebooted#45]
Hello can you give me more informations about this project? Im a graphic designer that contributes for opensource projects like yours, so if you need some help to create a logotype or other stuff just say it.

Greetings

**Comment by iceman1001** [comment]
This firmware repo might not be superinteresting to make logo or graphics to,  but the GUI repo could need some nicer icons :)  You find it here:   https://github.com/iceman1001/ChameleonMini-rebootedGUI

There is a clice-once deployment installing if you look in reademe file,   if you have trouble compiling code, for windows.
