### ISSUE TITLE
7 byte UIDs (?)

### ISSUE THREAD

**Issue by NeuerUser** [iceman1001/ChameleonMini-rebooted#48]
Hi

Sorry for being a noob here. Just got my RevE rebooted, because I wanted to do some experiments with Mifare Classic. The specs said something like "Mifare 1K (4-bit and 7-bit UID)" and "Mifare 4K (4-bit and 7-bit UID)". However, either I am stupid or the firmware only allows 4-bit Mifare emulation?

Again, sorry, if this is a stupid question.

Michael

**Comment by bogiton** [comment]
Hey there.
Have you enabled the CONFIG_MF_CLASSIC_1K_7B_SUPPORT and the CONFIG_MF_CLASSIC_4K_7B_SUPPORT configurations in the Makefile (or the Atmel project) before re-compiling/flashing? By default, these are turned off.

**Comment by iceman1001** [comment]
When I was looking through the memory layouts a few weeks back , I think that 7b uid will have problems.  Something about it reads uid from block0..   My conclusion of the current memory layout, is that it should be replaced in order to support the more interesting features of atqa/saK/uid/magic

**Comment by bogiton** [comment]
Hey man! I think you are right for the magic stuff. As for the uid, I haven't never tested the 1K/4K with 7B, so I'm not sure. The configuration declarations seem legit though.

**Comment by iceman1001** [comment]
yup,  also something they said it only read from flashmem every now and then into a ram buffer,  but the code shows its read/writes every time to flashmem.
Good thing the flashmemory is much larger than we thought :)

**Comment by bogiton** [comment]
I really want to find some time and play with that unused memory. Would be a great addition to the firmware. But first I think we have to address the issue about the recognition from the real readers. Could be related to that constant read/write in the flash memory, as you have said.

**Comment by devedse** [comment]
@iceman1001 , is this already implemented?

**Comment by iceman1001** [comment]
there is some support in firmware,  I haven't tested it or know more of it.

**Comment by mr-reb00t** [comment]
Hi  I just bought the Chameleon since 1 week ago, I just enable the CONFIG_MF_CLASSIC_1K_7B_SUPPORT in the firmware an "flashed it" to the chameleon.
Now in the GUI I am trying to clone a Mifare 1K 7B from SALTO (I upload the dump and everything is ok) but when I write the UID and "Apply" in the gui with my id "**04B2ABC24D5380**" it's change by an default UID like "1122334444FFFF"

[https://image.prntscr.com/image/YIub5VVHTj6lW4gU3_8DEA.png](url)

I just missed something more I need to do?
Thanks and sorry for my english :(

**Comment by exander77** [comment]
Does not work for me either.

**Comment by bogiton** [comment]
@acoman So, it doesn't accept any UID other than the 1122334444FFFF? Apart from the incorrect UID, does it work as it should (acting like a MFC 1K tag) against a reader? Also, is the UID you need also in the dump you are trying to upload? You shouldn't have to set the UID after you upload a proper dump under normal circumstances.

**Comment by mr-reb00t** [comment]
Hi @bogiton 
Nope, it's change  every time I set the UID it's changing by a default one like : 2B2F1163C76F72 or 1122334444FFFF, with the reader It's simulate MFC 1K 7 bytes but with the default UID.
Yes, the UID I need it is in the dump I upload too.
I just tried some solutions like that, first upload and after set the UID with different firmware version (custom version) and different software gui versions but no success , same problem :(

Dump link: **https://mrrobot.us/UID_0428B552E35D80_2019-05-13_13-35-51**  (generated with android mi fare classic tool)

UID I want: 0428B552E35D80

I just found one more problem, when I upload the dump, i just get the message "[+] File upload ok
" but when I download the dump it's not complete

Link of downloaded dump after uploaded: https://mrrobot.us/downloaded-after-upload

Thanks.

**Comment by exander77** [comment]
I can look into it, I want it to work. I would also like to migrate Desfire functionality from dev-zzo from the original firmware.

@iceman1001 I am kind of pissed, that this repository is not a fork of the original repository, what is the reason? It complicates merging functionality a lot. Also, can the rebooted version be flashed on Linux, I failed so far and have to flash on Windows? I own the Kickstarter version from Timo&Kasper as well and flash on Linux no problem. I bought the rebooted version a few days ago.

**Comment by exander77** [comment]
@acoman I have the exact same problem, btw. It is a firmware issue. The code for 7 byte ID was not maintained.

**Comment by mr-reb00t** [comment]
@exander77 I think it is but I didn't have too much knowleges for coding in C and fix that :(

**Comment by exander77** [comment]
I blamed firmware, but it is a GUI problem. It has some stupid check, that if the id does not have appropriate length, it fallbacks to default UID. I can send a pull request for GUI which fixes that.

**Comment by exander77** [comment]
@acoman Interested in testing it?

**Comment by exander77** [comment]
You have to build from sources both GUI and FW:
https://github.com/exander77/ChameleonMini-rebooted
https://github.com/exander77/ChameleonMini-rebootedGUI

**Comment by iceman1001** [comment]
@exander77   You don't need to use this repo. Nor the GUI either. No need to use anything that makes you pissed.  I rather not have you pissed.

**Comment by mr-reb00t** [comment]
> You have to build from sources both GUI and FW:
> https://github.com/exander77/ChameleonMini-rebooted
> https://github.com/exander77/ChameleonMini-rebootedGUI

I will try it today, thanks!

**Comment by exander77** [comment]
@acoman If you have troubles with compiling anything, I can send you a precompiled version.

**Comment by mr-reb00t** [comment]
> @acoman If you have troubles with compiling anything, I can send you a precompiled version.

I would appreciate it if you can send me the compiled version of the gui.

Thanks

**Comment by exander77** [comment]
@acoman https://nextcloud.shy.cz/index.php/s/SLTAijS9Y49G7gg

**Comment by exander77** [comment]
@acoman Do you need firmware as well?

**Comment by mr-reb00t** [comment]
> @acoman Do you need firmware as well?

Yes please!

**Comment by exander77** [comment]
@acoman 

It is built with these options:
```
SETTINGS    += -DCONFIG_MF_CLASSIC_1K_SUPPORT
SETTINGS    += -DCONFIG_MF_CLASSIC_1K_7B_SUPPORT
SETTINGS    += -DCONFIG_MF_CLASSIC_4K_SUPPORT
SETTINGS    += -DCONFIG_MF_CLASSIC_4K_7B_SUPPORT
SETTINGS    += -DCONFIG_MF_ULTRALIGHT_SUPPORT
SETTINGS    += -DCONFIG_MF_DETECTION_SUPPORT

SETTINGS  += -DDEFAULT_CONFIGURATION=CONFIG_NONE
```
Everything is here (including GUI): https://nextcloud.shy.cz/index.php/s/PknwW4cTrc8tswg

**Comment by exander77** [comment]
I backported also Desfire made by dev-zzo, but it does not fit with everything else, and it is not complete.

**Comment by exander77** [comment]
It contains changes from the original ChameleonMini repository from emsec as well.

**Comment by mr-reb00t** [comment]
> @acoman
> 
> It is built with these options:
> 
> ```
> SETTINGS    += -DCONFIG_MF_CLASSIC_1K_SUPPORT
> SETTINGS    += -DCONFIG_MF_CLASSIC_1K_7B_SUPPORT
> SETTINGS    += -DCONFIG_MF_CLASSIC_4K_SUPPORT
> SETTINGS    += -DCONFIG_MF_CLASSIC_4K_7B_SUPPORT
> SETTINGS    += -DCONFIG_MF_ULTRALIGHT_SUPPORT
> SETTINGS    += -DCONFIG_MF_DETECTION_SUPPORT
> 
> SETTINGS  += -DDEFAULT_CONFIGURATION=CONFIG_NONE
> ```
> 
> Everything is here (including GUI): https://nextcloud.shy.cz/index.php/s/PknwW4cTrc8tswg

Thanks, I will try it right now!

**Comment by mr-reb00t** [comment]
> It contains changes from the original ChameleonMini repository from emsec as well.

Super!

I still have a problem, the UID now it's working as well, but when I try tu upload my dump automatically the mode changes to MF 1K.

May you try it please?
My test dump.

Thanks.-

**Comment by exander77** [comment]
@acoman Will look into that. From the top of my head, the GUI does not take into account 4K on some places and it needs to be amended.

**Comment by iceman1001** [comment]
@NeuerUser  @acoman   Has your issue resolved itself using latest source from today?

**Comment by mr-reb00t** [comment]
Hi @iceman1001, thank you for your time.

When I'm trying to compile the latest version with this parameter enabled in Makefile
"SETTINGS    += -DCONFIG_MF_CLASSIC_4K_7B_SUPPORT"

I get this error on make
Configuration.c:196:25: error: ‘MifareClassicAppInit4K7B’ undeclared here (not in a function)

And The Chameleon Mini RevE Rebooted_en.exe (updated version) it doesen't connect with my device.

I'm still using this one https://github.com/iceman1001/ChameleonMini-rebootedGUI

**Comment by securechicken** [comment]
@NeuerUser @acoman please try now and close issue if fixed :)

**Comment by mr-reb00t** [comment]
Now I can compile but when I use the Chameleon Mini RevE Rebooted_en.exe (the latest version of this repo it doesen't connect with the device 

I need to use this version https://github.com/iceman1001/ChameleonMini-rebootedGUI it connects but when I'm trying to upload a dump it's change automatically to 1K and the dump is incomplete 

I think the problem is the rebootetGUI too :(

It works better with the version posts @exander77 

Everything is here (including GUI): https://nextcloud.shy.cz/index.php/s/PknwW4cTrc8tswg

**Comment by iceman1001** [comment]
I suppose the firmware detection in the GUI needs to fit the modified fw string..
now it needs to take all previous ones and ucrrent one in consideration.. o the love of renaming things just because...  Not mentioning to inform all other projects that we changed FW string again..  How tells Project Walrus?

**Comment by securechicken** [comment]
@iceman1001 not related. This 7B issue was just a compile issue, that has been fixed as a compile issue for now (and confirmed by issue opener - could we close 😀?) As for the FW string modification in return to VERSION command, it does not change the string that "modern" GUI searches for. I tested with rebootedGUI and current Lab401 provided GUIs (starting 1.1.0.1). The GUI @acoman is using is from long not compatible with this repo's FW (and FW string), and is just let on this repo for archive purpose on initial repo I think. It also does not handle 7B formats... As for Walrus, I did not find any search to a fixed string related to "Chameleon", so I guess this is still OK.

@acoman: you rely on an obsolete version of GUI, provided by manufacturer or reseller, and that is not compatible with this repo FW, as well as does not provide 7B UID function. As for the issue you encounter with rebootedGUI, it is probably because you must hit "apply" after changing a slot configuration, before uploading a dump. I could not reproduce your issue. Please read Wiki for any starting use and flashing scenario help and walkthrough.

**Comment by mr-reb00t** [comment]
@shinhub I'm using this one the latest version (https://github.com/iceman1001/ChameleonMini-rebootedGUI ) because the version of this repo it's not working, as you tell it is not compatible with the latest version of the FW.

I think the FW problem is solved but still have a problem with the GUI.

When I just try to write the correct UID like 0428B552E35D80 and aply it's change automatically to a default UID, and when I upload the dump it does some strange things, after that I download the dump and it's incomplete, if you have time just try it with my file dump and UID.

Thanks and sorry for my english.


> Hi @bogiton
> Nope, it's change every time I set the UID it's changing by a default one like : 2B2F1163C76F72 or 1122334444FFFF, with the reader It's simulate MFC 1K 7 bytes but with the default UID.
> Yes, the UID I need it is in the dump I upload too.
> I just tried some solutions like that, first upload and after set the UID with different firmware version (custom version) and different software gui versions but no success , same problem :(
> 
> 
> UID I want: 0428B552E35D80
> 
> I just found one more problem, when I upload the dump, i just get the message "[+] File upload ok
> " but when I download the dump it's not complete
> 
> 
> Thanks.

**Comment by iceman1001** [comment]
I am not sure to follow @acoman  problems anymore.
let's start over,    show me a picture of your termnal (like from inside the GUI, there is a tab)  running VERISION command.

..next I would say it sounds it is related to the GUI than this repo.. Since we enabled 7b UID ....

**Comment by mr-reb00t** [comment]
Sure, here you have the screenshot : https://image.prntscr.com/image/S2lECT4wTDizvC4S5sMSuQ.png

**Comment by iceman1001** [comment]
That link doesn't work :(

**Comment by securechicken** [comment]
@iceman1001 @acoman I could not reproduce what has been told.
Maybe there is an issue setting the 7 bits UID manually.
I do not understand what @acoman want to do.
If it is loading a DUMP : using a proper GUI (rebootedGUI), select your slot, put it as 4K 7b UID, hits "Apply". Then 'Upload Dump'. Then eventually if you need it sets 7b UID by hand on same slot, and hits apply.
The fact that you get a random UID at first is "normal".

**Comment by mr-reb00t** [comment]
https://imgur.com/a/dYuXEFT

https://i.imgur.com/fgVvD4c.gif

**Comment by iceman1001** [comment]
There seem to be several minor issues with the GUI...  
Try to set 7B mode in the serial tab for slot 1

**Comment by securechicken** [comment]
@acoman well that's a thing... It does not react like that from my side. It looks like your active state is changing, and that you have a memory overlap on top of that.
Could you give us the result of your SPI_FLASHINFO command, as well as maybe a picture of your device?

@iceman1001 there is however a bug right now, cause 4K works on 1st slot only, but 4k_7b is available everywhere.

**Comment by securechicken** [comment]
@iceman1001 I do not have this issue, if it is a GUI one... 
@acoman also please confirm this is Iceman rebootedGUI, and not the fork from exander77

**Comment by iceman1001** [comment]
aha.  I forgot about that fork...
Pretty soon I will need to compile and test myself.  I have too much to fiddle with the proxmark repo..

**Comment by mr-reb00t** [comment]
@iceman1001 if I set it in the serial mod with commands it is work, thanks!

@shinhub SPI_FLASHINFO result and uid set in serial mode.
https://imgur.com/kdLihE9

Pictures of my device:
https://imgur.com/a/UCx3nKM

And yes, I'm using the iceman fork, the another one was only for some tests.

Thanks.

**Comment by iceman1001** [comment]
Ok,  if it works in  serial mode,  then its not an issue of the Firmware.
but it seem to be an issue of the GUI.   Did you compile it yourself?  or did you use the precompiled?

**Comment by mr-reb00t** [comment]
@iceman1001 I use the precompiled version from this link: http://www.icesql.se/download/ChameleonMiniGUI/publish.htm

**Comment by securechicken** [comment]
@acoman thanks you. I cannot unfortunately explain what happens (I use the same GUI version as you...), sorry for that, but glad it worked.

@iceman1001 to fiddle with pm3? Yeah what happened by the way, I had to revert to whatever previous commit for it to be recognized, somewhere between 8th of August and today :)

**Comment by mr-reb00t** [comment]
Thanks for everything guys, now I can still playing with my device!
@shinhub @iceman1001

**Comment by iceman1001** [comment]
Ok,  the precompiled version doesn't support 7B  :)
You would need to compile it yourself.    Or get the artifact from appveyor...
I need to push out a new version..  @shinhub   if email me, the comms would be easier...

**Comment by securechicken** [comment]
@iceman1001  I did email you... to the mail on your profile (I didn't know if we could PM of sort of on GitHub, I'm new to this), on Thu, 15 Aug 2019.
And I have the same GUI version than acoman, without this bug, I definitely did not compile it myself, I grabbed it in release pages I think.

**Comment by iceman1001** [comment]
hm.. try sending to the iuse.se one more time.  
easy chat,  https://webchat.freenode.net/?channels=#proxmark3  IRC channel...
