### ISSUE TITLE
DFU driver (ATxmega32A4U) problems on WIN10 - 

### ISSUE THREAD

**Issue by geiraage** [iceman1001/ChameleonMini-rebooted#50]
When I try to set the device from normal mode to DFU via GUI, a unknown decvice pops up in Device manager.

It I try to update manualy, and I point it to Chameleon Mini Rebooted GUI\ChameleonMini-rebooted-master\Drivers\DFU Driver (include subfolder), 
Its starts to install ATxmega32A4U, but it fails saying The system cannont find the file specified..

Its all files needed located in the repo?

**Comment by bogiton** [comment]
Now that you mentioned it, I think there is a DLL missing from the repo. Try this and let me know if it works, so that I can update the repo with it.

[DFU Driver.zip](https://github.com/iceman1001/ChameleonMini-rebooted/files/2187782/DFU.Driver.zip)

**Comment by adrienafl** [comment]
For your information the driver I used was in the dfu-programmer archive downloaded from original repo.

**Comment by slurdge** [comment]
@bogiton The attached file works, so you can update the repo!

**Comment by bogiton** [comment]
@slurdge Thanks for the confirmation!
