### ISSUE TITLE
The ChameleonMini can't detect the password 

### ISSUE THREAD

**Issue by ghost** [iceman1001/ChameleonMini-rebooted#51]
When my device uses the detection function, I use Proxmark3 as the card reader. The ChameleonMini can't detect the password under your firmware (the calculation result is empty), but it can be used under other firmware.

**Comment by kgamecarter** [comment]
I have same problem too.
proxmark3 even can't select card when ChameleonMini detection.

**Comment by iceman1001** [comment]
Does the "mf detection" mode still have issues?   Or can we close this issue?
