### ISSUE TITLE
Automatic builds of the firmware

### ISSUE THREAD

**Issue by jlirochon** [iceman1001/ChameleonMini-rebooted#55]
Hey @iceman1001,

Is it legally possible to publish binaries of the firmware ?

If it's legally possible and you are OK, I can help with the automation (automatic builds upon GitHub push).

**Comment by iceman1001** [comment]
Sure,  why not?

**Comment by jlirochon** [comment]
Great, go for it ! You can flag this with `enhancement` :)

**Comment by iceman1001** [comment]
Just make it, bro!  I will merge it

**Comment by iceman1001** [comment]
What happend with automatic builds!?!  @jlirochon

**Comment by slurdge** [comment]
I had a look and ended up with this travis.yml file that does work for me.

https://github.com/slurdge/ChameleonMini-rebooted/blob/master/.travis.yml

**Comment by iceman1001** [comment]
PR?

**Comment by slurdge** [comment]
Sure, but I think you and/or @bogiton would need to setup the appropriate travis-ci key to be able to push here. Also, do you prefer it squashed or as is ? I did quite a lot of trial/errors :-p

**Comment by iceman1001** [comment]
squash please ;)
I think I already have a travis-ci key,  from the proxmark repo.    Shouldn't be too hard to set it up.
Or did you do that branch "travis-ci" solution?

**Comment by slurdge** [comment]
Nah I didn't do the branch solution. I'm not completely fluent in how the travis-ci keys work, so you have need some adjustments (strangely I have double builds done on my fork).

**Comment by iceman1001** [comment]
turns out I have travis-ci already setup prepped already for this repo.   Lets see how to get it to work

**Comment by iceman1001** [comment]
I think we have success?!?!

![image](https://user-images.githubusercontent.com/8577004/53258858-f4840880-36cd-11e9-8578-1380d3d86ca1.png)

**Comment by iceman1001** [comment]
I can see some problems with this in the long run.
Alot of releases and strange naming convention.
