### ISSUE TITLE
Out of bound for SPI_FLASH_INFOMY

### ISSUE THREAD

**Issue by slurdge** [iceman1001/ChameleonMini-rebooted#56]
If you look at https://github.com/iceman1001/ChameleonMini-rebooted/blob/master/Firmware/Chameleon-Mini/Terminal/Commands.h#L61, you will see that the max length for a command is  `16`. But this should be including the final `0`.
As `len("SPI_FLASH_INFOMY") == 16`, when displaying commands or interpreting them there is an out of bound access to the next member of the struct, `ExecFunc`.
We should either do a +1 inside the struct to accomodate for the final `0`:
```C
char Command[MAX_COMMAND_LENGTH + 1]; //for final \0
```
or change the value of `MAX_COMMAND_LENGTH`.

However my board is still dead so I can't test&propose a PR right now. This bug is just a reminder that this should be checked in the future.

**Comment by iceman1001** [comment]
Good catch.
I suggest change MAX_COMMAND_LENGTH
Make PR?

**Comment by slurdge** [comment]
I can make the PR, but I really dislike PR without testing first... So I'll try to unbrick my device first.

**Comment by slurdge** [comment]
Since I could reprogram my unit, I could test the change.
Unfortunately, changing `MAX_COMMAND_LENGTH` does not work. Since it's in PROGMEM, I believe there's an issue that this struct is strangely overlapping other stuff. 100% of the time, if `MAX_COMMAND_LENGTH > 16`, then the 8th entry does not work (and that probably how I bricked my unit in the first place, added with other bugs ?).

So, reducing the command by 1 byte is much safer and easier IMO. I'll also put a warning regarding the size in the PR.
