### ISSUE TITLE
GUI source code

### ISSUE THREAD

**Issue by iceman1001** [iceman1001/ChameleonMini-rebooted#7]
I've asked the manufacturer about getting the source code for the GUI.  They said they will look into it.

It is a start.

**Comment by ghost** [comment]
Great. We’ll look forward.

**Comment by iceman1001** [comment]
Some bad news, 
The student who wrote the GUI does not want it to be open-sourced...  

I guess I will have to write my own GUI....

**Comment by ghost** [comment]
Too bad. So we need to make our own. 
I'll take a closer look to it if I find some time between family and job.
December is really stressful :-)

**Comment by iceman1001** [comment]
I know.  Time is always short when it comes to these things.

**Comment by kevin2008-01** [comment]
i search for partial decompile it. see you later.

**Comment by iceman1001** [comment]
Part success! 
I got the gui code for monitoring the device.

**Comment by iceman1001** [comment]
https://pastebin.com/3Y6SGFi9

**Comment by iceman1001** [comment]
I seem to forgotten, but someone sent me their own GUI.   **ChameleonMiniGui v0008_s_2.exe**
I managed find time to play with it now.  It has some interesting features.  
It would be nice having both the rebooted gui and this one.   There is potential here!

And all those minor issues with missing libs,  either VC++ (different languages)  or mscorlibs..
This needs to be adjusted so all pre-compiled software gets a nice package.  Much windows tools in this.

**Comment by iceman1001** [comment]
And it was from @kevin2008-01   in another issue.   Perfect,  does this GUI come from the original Chameleon Mini repo or?!?

**Comment by kevin2008-01** [comment]
yes sure, original. just do it iceman......

**Comment by kevin2008-01** [comment]
i don't test with boomerang for decompil it. If i have time i test for you.

**Comment by bogiton** [comment]
Is it possible to get any more source code for the GUI or it would be better to start building one from scratch? Maybe in another language too, like C#? What do you guys think?

**Comment by iceman1001** [comment]
I suspect a brand new GUI based on C# would be the best.  
However getting inspiration from existing GUI's    Taking the best parts and drop the rest.

1. one advantage with this rebooted is the mfkey attack implemented.  So getting those attack inside it would be good.  
2. the current chameleon can do much on the deviceside.  Which is encouraged.
3. save / loading / comparing dumps.
4. creating / converting dumps between MCT/PM3/LIBNFC etc.

**Comment by kevin2008-01** [comment]
==> Iceman, great !!!! What do you want....
I discuss with papy, and according for christmas, i receive one VIGIK VTI25M for testing the chameleon.... MF Detect.... Ready please.....
Please implement +1 / -1 UID, and for the future roll'up...
Sincerely.

**Comment by iceman1001** [comment]
Vigik ?  hm,  chameleon has problems with faking a card against it.
Some of the fixes needed is,  respond with a different sak then inside s0-block0.

**Comment by bogiton** [comment]
@iceman1001 I started working on the C# GUI we were discussing. Which is the best way to share this? PR?

**Comment by bogiton** [comment]
[ChameleonMiniRebootedGUI-alpha_source.zip](https://github.com/iceman1001/ChameleonMini-rebooted/files/1572008/ChameleonMiniRebootedGUI-alpha_source.zip)

This was easier for me, hope you don't mind.

**Comment by iceman1001** [comment]
The question is good.  Shall we have a new repo for it?

**Comment by bogiton** [comment]
I suppose we could just include it under the /Software/ folder.

**Comment by iceman1001** [comment]
well.. it depends on how big it will become?  no?

**Comment by ghost** [comment]
I think an own repo will be good, links can be added to each other. So we can maybe develop the GUI fore more purposes. What do you think?

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
An 19. Dez. 2017, 16:01, Iceman schrieb:

**Comment by iceman1001** [comment]
I do like the own repo,  with its own issues and wiki maybe..

**Comment by iceman1001** [comment]
And its up:   https://github.com/iceman1001/ChameleonMini-rebootedGUI

I will close this issue,   and add that pastebin link in a new issue there..

**Comment by iceman1001** [comment]
So this is the gui dude,   http://35b0.de/2017/12/18/chameleonmini-gui/
Is this @bogiton  or @kevin2008-01  ?!?

**Comment by bogiton** [comment]
Don't know what that is. I only uploaded it here. Is that for the rebooted version?

**Comment by iceman1001** [comment]
No,  that was someone elses GUI..  
Your contribution is the foundation in the new repo,  
https://github.com/iceman1001/ChameleonMini-rebootedGUI

**Comment by kevin2008-01** [comment]
this GUI no working with rebooted....

**Comment by iceman1001** [comment]
and that would be because its not a finished GUI software.  I'm sorry if that wasn't clear.
