### ISSUE TITLE
New firmware can't sniff password

### ISSUE THREAD

**Issue by libin-ka** [iceman1001/ChameleonMini-rebooted#75]
The latest firmware cannot sniff the password. When the previous firmware is sniffed, the corresponding indicator will flash. When the latest firmware sniffs, the corresponding card slot LED is always on.

**Comment by iceman1001** [comment]
Since its not sniffing passwords, but rather sniffing Mifare authentications online and step two is a offline recovery phase of key.  What did you do to?  Screenshots from software you are using?

**Comment by libin-ka** [comment]
The same read head, that is, the latest firmware can not sniff out the password, the factory-supplied firmware sniffing password can sniff the password.

**Comment by iceman1001** [comment]
see previous answer

**Comment by bogiton** [comment]
@libin-ka What kind of password you want to sniff? Mifare Classic? Are you using the Chameleon mini rebooted GUI?

**Comment by libin-ka** [comment]
> @libin-ka What kind of password you want to sniff? Mifare Classic? Are you using the Chameleon mini rebooted GUI?
chameleon Mini GUI -v1.2.0.14

**Comment by iceman1001** [comment]
What are you findings @bogiton  ?  You mention that MF_DETECTION  and PASSWORD sniffing didn't work??

**Comment by bogiton** [comment]
I am not sure what is happening with MF_DETECTION (or my device)... As soon as I set the configuration of a slot to that, the pm3 cannot select the card... I tested it with multiple combinations of firmware/GUI. Unfortunately, only the stock firmware worked for me. Anyone who has used this functionality with our firmware?
On the other hand, PWDMY works fine in the latest firmware.

**Comment by iceman1001** [comment]
did you fix this one @bogiton ?

**Comment by bogiton** [comment]
Should be the same as in issue #44 
Maybe @libin-ka can confirm if it works with the new firmware?

**Comment by libin-ka** [comment]
![20190308115002](https://user-images.githubusercontent.com/46210417/54006443-58abcf80-4198-11e9-8529-8cb9a5c3ac95.jpg)   device disconnect

**Comment by libin-ka** [comment]
![20190308115447](https://user-images.githubusercontent.com/46210417/54006604-00c19880-4199-11e9-94a8-20588ad90fdc.jpg)  v1.2.0.15   
Can connect, can sniff out the password

**Comment by bogiton** [comment]
Yeah, the old GUI is no longer supported in the newer firmware.
So, all good with the new one. Great! :)

**Comment by iceman1001** [comment]
GUI v1.2.15 works.  ok.  Time to close!
