### ISSUE TITLE
SAKMY set to 20 does not work

### ISSUE THREAD

**Issue by rgrunbla** [iceman1001/ChameleonMini-rebooted#76]
Hi,
I'm trying the new features (SAK and ATQA settinggs). ATQA is working as expected (it seems), but for the SAK, setting it to 20 stops the chameleon mini (rev e) from working. Is that expected? The SAK seems updated, but an external reader does not succeed in reading the chameleon mini, while it works with the SAK to 19 for example.
```
SAKMY=20
100:OK
SAKMY?
101:OK WITH TEXT
20
```
```
% sudo nfc-list
nfc-list uses libnfc 1.7.1
NFC device: ACS / ACR122U PICC Interface opened
%
```

When set to 19:

```
% sudo nfc-list
nfc-list uses libnfc 1.7.1
NFC device: ACS / ACR122U PICC Interface opened
1 ISO14443A passive target(s) found:
ISO/IEC 14443A (106 kbps) target:
    ATQA (SENS_RES): 12  34  
       UID (NFCID1): 12  34  56  78  
      SAK (SEL_RES): 19  
```

**Comment by iceman1001** [comment]
Do you randomly set SAK and ask why a reader think the anticollision phase failed?

**Comment by rgrunbla** [comment]
No, I don't randomly set it. I set it to what is read by an acr122u when scanning a mifare desfire card.

This is not random at all: http://nfc-tools.org/index.php/ISO14443A

I think if a value is not supported, the Chameleon Mini should not answer with "101:OK WITH TEXT".

**Comment by iceman1001** [comment]
did you know that ATQA/SAK works together?

If you want to add a check that verifies all possible valid combos of ATQA/SAK and add it into the firmware,  feel free to contribute!

**Comment by rgrunbla** [comment]
That's why I tested ATQA/SAK that should works together, as listed on the http://nfc-tools.org/index.php/ISO14443A.

For example, 03 44 ATQA + 20 SAK does not work, but it should (or at least, some real world cards are using this).

**Comment by iceman1001** [comment]
Your original post doesn't show any signs on which ATQA values you used, more than 12 34.
In order to figure out if this is a bug or not,  traces of communications and steps / values you have done, set.

**Comment by rgrunbla** [comment]
So

1. I cloned this repo, compiled the firmware, and put it on a chameleon mini rev e.
2. I executed these commands:

```
HELPMY
101:OK WITH TEXT
VERSIONMY,CONFIGMY,UIDMY,ATQAMY,SAKMY,READONLYMY,UPLOADMY,DOWNLOADMY,RESETMY,UPGRADEMY,MEMSIZEMY,UIDSIZEMY,BUTTONMY,BUTTON_LONGMY,SETTINGMY,CLEARMY,HELPMY,RSSIMY,PWDMY,DETECTIONMY,SPI_FLASHINFOMY
VERSIONMY?
101:OK WITH TEXT
Chameleon Mini Rebooted v1.2 (Iceman)
CONFIGMY
101:OK WITH TEXT
CLOSED,MF_ULTRALIGHT,MF_ULTRALIGHT_EV1_80B,MF_ULTRALIGHT_EV1_164B,MF_CLASSIC_1K,MF_CLASSIC_1K_7B,MF_CLASSIC_4K,MF_DETECTION
CONFIGMY=MF_ULTRALIGHT
100:OK
UIDMY=11223344112233
100:OK
UIDMY?
101:OK WITH TEXT
11223344112233
ATQAMY=0344
100:OK
ATQAMY?
101:OK WITH TEXT
0344
SAKMY=20
100:OK
SAKMY?
101:OK WITH TEXT
20
SAKMY?
101:OK WITH TEXT
20

```

Using nfc-list -v, this is what I get:

```
nfc-list uses libnfc 1.7.1
NFC device: ACS / ACR122U PICC Interface opened
1 ISO14443A passive target(s) found:
ISO/IEC 14443A (106 kbps) target:
    ATQA (SENS_RES): 03  44
* UID size: double
* bit frame anticollision supported
       UID (NFCID1): 11  22  33  44  11  22  33
      SAK (SEL_RES): 00
* Not compliant with ISO/IEC 14443-4
* Not compliant with ISO/IEC 18092

Fingerprinting based on MIFARE type Identification Procedure:
Other possible matches based on ATQA & SAK values:
* Unknown card, sorry
0 Felica (212 kbps) passive target(s) found.
0 Felica (424 kbps) passive target(s) found.
0 ISO14443B passive target(s) found.
0 ISO14443B' passive target(s) found.
0 ISO14443B-2 ST SRx passive target(s) found.
0 ISO14443B-2 ASK CTx passive target(s) found.
0 ISO14443A-3 Jewel passive target(s) found.
0 ISO14443A-2 NFC Barcode passive target(s) found.

```

Tell me if you need more information.

**Comment by bogiton** [comment]
I think it is working ok. When I set it to the default MF_CLASSIC_1K configuration (with SAK = 08) from the GUI, I get the following output from pm3:
```
pm3 --> hf 14a info
 UID : 11 22 33 44
ATQA : 00 04
 SAK : 08 [2]
TYPE : NXP MIFARE CLASSIC 1k | Plus 2k SL1 | 1k Ev1
```
Then I issue the `SAKMY=88` command from the serial terminal and I get the following from pm3, as expected:
```
pm3 --> hf 14a info
 UID : 11 22 33 44
ATQA : 00 04
 SAK : 88 [2]
TYPE : Infineon MIFARE CLASSIC 1K
```
Please correct me if I'm wrong, but I think that the Mifare Desfire configuration you are trying (with ATQA 0344 and SAK 20) requires different handling from the firmware, which we don't support yet.

**Comment by rgrunbla** [comment]
> Please correct me if I'm wrong, but I think that the Mifare Desfire configuration you are trying (with ATQA 0344 and SAK 20) requires different handling from the firmware, which we don't support yet.

Do you have an idea where to start? I believe the ISO14443ASelect should work with no regard for the SAKValue, but that might be elsewhere.

And, for your example, indeed it works with some value, but in my case I specifically want to "emulate" a desfire card, a little bit like what is done by some cards such as this one https://www.rfxsecure.com/product/7byte-uid-changeable-card-with-desfire-sakatqa/

**Comment by bogiton** [comment]
I guess you'll have to wait until we add support for MF_DESFIRE :)

**Comment by rgrunbla** [comment]
Yeah, but I mean, cannot I get a sak equal to 20 even if i'm not using MF_DESFIRE, but only MF_ULTRALIGHT ? That seems weird to me, as 0x20 is not really bigger than 0x88 for example. Why does it fails? I suspect even not implementing the full MF_DESFIRE "stack", just being able to "lie" on the SAK / ATQA using another protocol might open many « doors ».

**Comment by iceman1001** [comment]
close because of inactivity
