### ISSUE TITLE
How to emulate HID proxcard?

### ISSUE THREAD

**Issue by dealaddict** [iceman1001/ChameleonMini-rebooted#78]
Sorry for the noob question but does Chameleon emulate a HID proxcard? Its not even reading on my ACR122U. I tried also with a phone and same no go. I guess its not just my chameleon as even my ACR is not able to read it? But lets say if I do find a way to somehow read the data and upload a bin will it work for Chameleon?

**Comment by iceman1001** [comment]
... HID proxcards is LF

**Comment by dealaddict** [comment]
So that means its not supported by Chameleon? Do you know if its the same for ACR122U as well? @iceman1001 what would I need to buy to copy this LF?
