### ISSUE TITLE
"BOOT_LOADER_EXE.exe" can't find device in DFU mode.

### ISSUE THREAD

**Issue by septs** [iceman1001/ChameleonMini-rebooted#82]
DFU mode is enabled
![image](https://user-images.githubusercontent.com/3842474/53882495-702c7080-4051-11e9-9d51-d5f28d143029.png)

Running `BOOT_LOADER_EXE.exe` can't find device
![image](https://user-images.githubusercontent.com/3842474/53882475-6276eb00-4051-11e9-8a85-c11406bc569a.png)

"dfu-old-driver: no device present"

------------------

Windows 10 (1809)
Surface Pro (5th Gen)

**Comment by septs** [comment]
Rebuilding `libusb0.dll` can solve this problem

see https://github.com/libusb/libusb/wiki/Windows

**Comment by ensingerphilipp** [comment]
@septs  What do you mean with rebuilding this dll? Can you provide me with instructions? (am a complete N00b at this) Thanks :)
