### ISSUE TITLE
MF Classic Emulation BROKEN

### ISSUE THREAD

**Issue by ensingerphilipp** [iceman1001/ChameleonMini-rebooted#86]
Hi :)

So i was trying to emulate 2 different kinds of MFC 1k today and sadly had to see that it is **not working realiably AT ALL**
I did the following:

1. Upgrade Firmware to Iceman 1.3 (Also affects Stockfirmware)
2. Upload .mfd dump file to slot, choose MFC 1K & hit apply

--> When presenting the Reader with the Card it does not react
turns out when trying to read the chameleon with my smartphone it showed correct UID SAK and ATQA but sectors where randomly seen as unreadable - sometimes reading sectors succeeded but never all of them
--> For my usecase the reader must be able to read the chameleon correctly in order to work as parts for the key generation of the reader are in some sectors (not only UID)

Might this be a timing / hardware issue or has anyone resolved it?
**_Sectors seem to be randomly readable or unreadable_**

Hope someone can help me 😁

Best regards

**Comment by iceman1001** [comment]
Did you use the GUI for uploading?

**Comment by ensingerphilipp** [comment]
Yes i used your newest Version of Chameleon GUI v12.0.19
(also tried the Lab401 Current Version - which also did not work)

Are you aware of this issue - where there already other reports on it ?

**Comment by iceman1001** [comment]
ok,  verified.    The gui isn't the problem. 
using mini and pm3. 
On latest firmware the 14a is slow and acting strange.  can do **hf mf fchk** to get all keys, but the dumping doesn't work.

revert to stock firmware and **hf mf fchk** / **hf mf dump**  works good.

**Comment by ensingerphilipp** [comment]
Ok thanks i will try - where do i get the stock Firmware? / Would you be able to provide me with the .bin or .eep .hex files?

**Comment by ensingerphilipp** [comment]
Sadly using Stock Firmware (provided in the GUI) did not resolve the problem

//EDIT//

Works better - but not resolved -->
With very fault tolerant Door-Reader it now is working (after waiting for 2-5 seconds)
With other Reader sadly not (and different Dump and Key generation Process that needs severel sectors read correctly before decrypting)

By trying to read via smartphone it still loses some sectors aswell (some = 70% of what it lost before so still much)

**Comment by securechicken** [comment]
@eXspir3 you should try with firmware compiled from today. A lot have been fixed. Note that some readers still do not react, but if this is still the case for you, you should be able to narrow it to a test case you could describe.

**Comment by iceman1001** [comment]
time to close?

**Comment by ensingerphilipp** [comment]
unfortunately i cant test right now - pls close
