### ISSUE TITLE
Chinese magic backdoor command

### ISSUE THREAD

**Issue by Ollibolli85** [iceman1001/ChameleonMini-rebooted#99]
Hello everybody,

does the Chameleon Mini send a "chinese magic backdoor command"?

Many thanks in advance!

**Comment by bogiton** [comment]
Hey there. Only if you explicitly set it in Makefile/Project and re-compile. It is the "SUPPORT_MF_CLASSIC_MAGIC_MODE" option.
By default, this is disabled.

**Comment by Ollibolli85** [comment]
Thank you!
